# In different sessions of the Illinois legislature, the same
# committee can have different names appear on http://ilga.gov/
# Sometimes this is just spelling of typographic, ("Agriculture &
# Conservation" vs "Agriculture and Conservation"). Sometimes the
# difference is larger. The COMMITTEES dictionary can be used for
# resolving these different names to to the same committee.  The keys
# of COMMITTEE are a tuple of the 'Name' and 'Code' of the committee
# as they appear on http://ilga.gov/senate/committees/default.asp or
# http://ilga.gov/house/committees/default.asp. The values are arbitrary ints, used only
# within the scraper as a unique identifier for the actual committee.

# HIGHEST ID POSSIBLY IN USE: 1132

COMMITTEES = {('8th District Education Oversight Su', 'HAPE-HDEO'): '97',
              ('Access to Federal Funding', 'HAFF'): '98',
              ('Accountability & Administrative Rev', 'HAAR'): '99',
              ('Accountability, Subcommittee on Ele', 'HELM-ACCT'): '100',
              ('Adoption Reform', 'ADPT'): '2',
              ('Adoption & Child Welfare', 'HACW'): '2',
              ("Affordable Alzheimer's Services", 'HHCL-AASE'): '101',
              ("Alzheimer's Disease Task Force", 'ADTF'): '106',
              ("Exec. Subcommittee - St./Loc. Gov't", 'SEXC-ESLG'): '206',
              ("O'Hare Airport Environmental Impact", 'HENH-OHAR'): '348',
              ("Spec. Comm. on Workers' Comp Reform", 'SWCR'): '432',
              ("Subcomm. Children's Health Issues", 'SNVR-SCEH'): '494',
              ("Subcomm.Adv.PracticeNurse's License", 'SLIC-SPNL'): '499',
              ("Veterans' Affairs", 'HVET'): '87',
              ("Worker's Compensation Subcommittee", 'HLBR-WCOM'): '641',
              ("Workers' Compensation Reform", 'HWCR'): '645',
              ("Workers' Compensation Subcommittee", 'HLBR-WORK'): '641',
              ("Workers' Compensation and Unemploy", 'HLBR-WCUI'): '91',
              ("Workers' Compensation", 'HLBR-WORC'): '641',
              ('Adoption Reform, Special Committee', 'ADPT'): '2',
              ('Agency Operations Subcommittee', 'HSGA-HAGO'): '102',
              ('Aging', 'HAGI'): '103',
              ('Agreed Labor Bills, Subcommittee', 'HLBR-AGLB'): '104',
              ('Agriculture & Conservation', 'HAGC'): '6',
              ('Agriculture & Conservation', 'SAGR'): '5',
              ('Agriculture and Conservation', 'HAGC'): '6',
              ('Agriculture and Conservation', 'SAGR'): '5',
              ('Agriculture', 'SAGR'): '5',
              ('Air Quality', 'HENE-AIRQ'): '9',
              ('Air Quality, Subcommittee on', 'HENE-AIRQ'): '9',
              ('Air Subcommittee', 'HENE-SAIR'): '9',
              ('Airports, Subcomittee on', 'HTRN-AIRP'): '10',
              ('Airports, Subcommittee on', 'HTRN-AIRP'): '10',
              ('Amendments', 'SHCA-HCAA'): '107',
              ('Amusement & Online Gaming Sub', 'HCDA-CAOG'): '1107',
              ('Analytics Subcommittee', 'HCBA-ALYT'): '108',
              ('Animal Baiting Subcommittee', 'HAGC-ANIM'): '60',
              ('Animals Subcommittee', 'HAGC-ANIM'): '60',
              ('Approp I', 'SAPA'): '14',
              ('Approp II', 'SAPB'): '15',
              ('Approp-Elementary & Secondary Educ', 'HAPE'): '109',
              ('Approp. Elementary and Second Ed.', 'HAPE-APES'): '1001',
              ('Appropriations I', 'SAPA'): '14',
              ('Appropriations II', 'SAPB'): '15',
              ('Appropriations III', 'SAPC'): '111',
              ('Appropriations-Capital', 'HCAP'): '1104',
              ('Appropriations-General Service', 'HAPG'): '112',
              ('Appropriations-Higher Education', 'HAPI'): '113',
              ('Appropriations-Human Services', 'HAPH'): '114',
              ('Appropriations-Public Safety', 'HAPP'): '115',
              ('Armed Forces & Military Affairs', 'HAMA'): '116',
              ('Assignments', 'SCOA'): '21',
              ('Assistance and Benefits Subcommitte', 'HHSV-ASBE'): '117',
              ('Ballot Access Subcommittee', 'HELE-BALL'): '118',
              ('Bio-Technology', 'HBIO'): '119',
              ('Biotechnology Committee', 'BIOT'): '119',
              ('Broadband Access and IT Assurance', 'HCDA-CBAI'): '1108',
              ('Broadband Infrastructure, Subcommit', 'HTEL-HBBI'): '121',
              ('Business & Occupational Licenses', 'HBOL'): '24',
              ('Business and Industry Regulations S', 'HLBR-LBIR'): '1109',
              ('Business Growth & Incentives', 'HBGI'): '122',
              ('Business Growth & Incentives', 'HSBG'): '122',
              ('Business Incentives for Local Comm.', 'HBIL'): '124',
              ('Business Licenses Subcommittee', 'HBOL-BLIC'): '125',
              ('Business Licenses Subcommittee', 'HBOL-BOBL'): '125',
              ('Business Licenses Subcommittee', 'HBOL-BULI'): '125',
              ('Business Occupational Licenses', 'HBOL'): '24',
              ('Business Regulation', 'HBOL-BREG'): '128',
              ('Campaign Finance Subcommittee', 'HELE-CAFI'): '129',
              ('Cemeteries Subcommittee', 'HJUA-CEME'): '130',
              ('Charter Schools Subcommittee', 'HELM-CHAR'): '33',
              ('Charter Schools', 'HELM-CHAR'): '33',
              ('Child Care Access & Early Childhood', 'HCEC'): '1105',
              ('Child Support Enforcement', 'HCSE'): '131',
              ('Childhood and Young Adult Onset Sub', 'HMEH-CHIL'): '132',
              ('Cities & Villages', 'HCIV'): '133',
              ('Civil Procedure Subcommittee', 'HJUA-CIPS'): '134',
              ('Civil Procedure Subcommittee', 'HJUA-JCIP'): '134',
              ('Civil Process Subcommittee', 'HJUA-HCIV'): '134',
              ('Civil Process and Procedures Subcom', 'HJUA-CIPP'): '134',
              ('Climate Change Subcommittee', 'HENE-CCHA'): '137',
              ('Coal Finance Subcommittee', 'HREF-HCOA'): '138',
              ('Com. Oversight Medicaid Mang. Care', 'SOMM'): '30',
              ('Comm. On State & Pension Fund Inves', 'SSPF'): '2274',
              ('Commerce & Business Development', 'HCBD'): '140',
              ('Commerce & Economic Development', 'SCED'): '64',
              ('Commerce and Economic Development', 'SCED'): '64',
              ('Commerce and Innovation Subcommitte', 'HLBR-LCIS'): '1110',
              ('Commerce', 'SCOM'): '139',
              ('Commercial Law Subcommittee', 'HJUA-COLS'): '141',
              ('Commercial Law Subcommittee', 'HJUA-JCLS'): '141',
              ('Committee of the Whole', 'HCWL'): '34',
              ('Committee of the Whole', 'SCWL'): '35',
              ('Committee on Housing', 'SSCH'): '157',
              ('Committee on Pension Investments', 'SSCP'): '142',
              ('Committee on Restorative Justice', 'SCRJ'): '143',
              ('Committee on Supplier Diversity', 'SCSD'): '648',
              ('Community Affairs', 'SHCA-SSCA'): '144',
              ('Community Care Program Subcommittee', 'HAGI-CARE'): '145',
              ('Community College Access & Afford.', 'HCCA'): '146',
              ('Compensation Subcommittee', 'HCOT-COMP'): '147',
              ('Computer Technology', 'HCOM'): '148',
              ('Conflicts of Interest', 'HCFI'): '149',
              ('Consolidated Subcommittee', 'HCOT-CONS'): '150',
              ('Consolidation & Tax Subcommittee', 'HCOT-CTCT'): '150',
              ('Constitutional Law Subcommittee', 'HJUA-JCDL'): '1111',
              ('Constitutionality and Redundancy', 'HJUB-CORE'): '151',
              ('Construction Industry & Code Enforc', 'HCIC'): '152',
              ('Consumer Health Subcommittee', 'HCON-COHE'): '153',
              ('Consumer Protection', 'HCON'): '154',
              ('Consumer Protection', 'SCCP'): '155',
              ('Consumer Regulation', 'HCON-HCRG'): '156',
              ('Consumer Regulation, Subcomittee', 'HCON-HCOR'): '156',
              ('Consumer Review Subcommittee', 'HCON-CRVW'): '158',
              ('Corrections Subcommittee', 'HJUB-CORR'): '159',
              ('Cost Analysis Subcommittee', 'HAPI-COST'): '160',
              ('Cost Benefit Analysis', 'HCBA'): '161',
              ('Counties & Townships', 'HCOT'): '162',
              ('Credit & Affordable Housing', 'SHCA-SCAH'): '41',
              ('Crim. Law Subcom Enhance/Redundancy', 'SCCL-SCER'): '163',
              ('Criminal Admin and Enforcement', 'HJUC-CRIM'): '164',
              ('Criminal Justice Reform Subcommitte', 'HREJ-HCJR'): '165',
              ('Criminal Law Subcomm. Const. Review', 'SCCL-SCCR'): '167',
              ('Criminal Law Subcomm. on Firearms', 'SCCL-SCCF'): '168',
              ('Criminal Law', 'SCCL'): '166',
              ('Criminal Procedure, Penalties', 'HJUA-CPPS'): '169',
              ('Cybersecurity, Data Analytics, & IT', 'HCDA'): '170',
              ('DCFS Oversight', 'HDCF'): '171',
              ('Deficit Reduction', 'SCDR'): '172',
              ('Develop Disabilities Mental Illness', 'HDMI'): '173',
              ('Disability Services', 'HDIS'): '174',
              ('Disparities in Educational Achievem', 'HDEA'): '175',
              ('Distributed Ledgers & Cryptocurrenc', 'HCDA-CDLC'): '214',
              ('Distributed Ledgers & Cryptocurrenc', 'HCDA-DLCS'): '214',
              ('Dog & Cat Pop. Control Adv. Comm.', 'DCPC'): '176',
              ('Domestic Relations Law Subcommittee', 'HJUA-DRLS'): '177',
              ('Drivers Education & Safety', 'HDES'): '178',
              ('Drugs Subcommittee', 'HJUB-DRGS'): '179',
              ('E & E Subcomm. on Chem. & Coal', 'SENV-SECC'): '180',
              ('Economic Development & Housing', 'HECD'): '47',
              ('Economic Development', 'HECD'): '47',
              ('Economic Growth and Mod. Sub.', 'HECD-HEGM'): '181',
              ('Economic Justice & Equity', 'HEJE'): '182',
              ('Economic Opportunity', 'HECO'): '183',
              ('Economic Opportunity & Equity', 'HECO'): '183',
              ('Education Policy & Procedure', 'SESE-SEPP'): '185',
              ('Education Reform', 'EREF'): '186',
              ('Education', 'SESE'): '184',
              ('Election Administration Subcommitte', 'HELE-ELEC'): '187',
              ('Elections & Campaign Finance', 'HELE'): '189',
              ('Elections & Campaign Reform', 'HECR'): '52',
              ('Elections and Campaign Reform', 'HECR'): '52',
              ('Elections', 'SELC'): '188',
              ('Electric Deregulation, Subcommittee', 'HENE-ELEC'): '190',
              ('Electric Generation & Commerce', 'HEGC'): '191',
              ('Electric Utility Oversight', 'HEUD'): '192',
              ('Electric and Natural Gas, Subcom', 'HPUB-ELEC'): '193',
              ('Elem Sec Ed: Adm., Lic. & Charter', 'HELO'): '56',
              ('Elem Sec Ed  Charter School Policy', 'HELC'): '53',
              ('Elem Sec Ed School Curricu Policies', 'HELM'): '54',
              ('Elem Sec Ed:  Charter School Policy', 'HELC'): '53',
              ('Elem Sec Ed: Licensing Oversight', 'HELO'): '56',
              ('Elem Sec Ed: Licensing, Admin.', 'HELO'): '56',
              ('Elem Sec Ed: School Curric Policies', 'HELM'): '54',
              ('Elementary & Secondary Education', 'HELM'): '54',
              ('End of Career Compensation Sub', 'HPPN-ENCC'): '195',
              ('Energy & Environment', 'HENG'): '196',
              ('Energy Management, Subcommittee', 'HHED-ENER'): '197',
              ('Energy Resources Subcommittee', 'HENE-ENRE'): '911',
              ('Energy and Public Utilities', 'SENE'): '59',
              ('Energy', 'HENG'): '196',
              ('Energy', 'SENE'): '59',
              ('Enhancement of Criminal Penalties', 'HJUB-EOCP'): '198',
              ('Enterprise Zone Extensions', 'SCEZ'): '199',
              ('Environment & Energy', 'HENE'): '62',
              ('Environment & Energy', 'SENV'): '49',
              ('Environment Subcommittee', 'HENE-ENVI'): '200',
              ('Environment and Conservation', 'SNVR'): '63',
              ('Environment and Energy', 'HENE'): '62',
              ('Environment and Energy', 'SENV'): '49',
              ('Environment', 'HENE'): '62',
              ('Environment', 'SNVR'): '63',
              ('Environmental Health', 'HENH'): '201',
              ('Environmental Justice Subcommittee', 'HENG-EJUS'): '1112',
              ('Environmental Quality Subcommittee', 'HENE-SEQU'): '202',
              ('Environmental Regulations Subcommit', 'HENE-ENRE'): '61',
              ('Ethanol Production Oversight', 'HEPO'): '203',
              ('Ex-Offender and Reentry Subcommitte', 'HAPP-EXOF'): '204',
              ('Exec. Subcomm. Fin/ Lic Activities', 'SEXC-ESLA'): '205',
              ('Exec. Subcommittee on Amendments', 'SEXC-EXSA'): '207',
              ('Exec. Subcommittee on Education', 'SEXC-ESOE'): '208',
              ('Exec. Subcommittee on Tobacco', 'SEXC-ESOT'): '209',
              ('Exec.Subcommitte on Gaming', 'SEXC-ESOG'): '210',
              ('Executive Appointments', 'SEXA'): '213',
              ('Executive Subcommittee on Amendment', 'SEXC-SXAM'): '207',
              ('Executive Subcommittee on Education', 'SEXC-SXED'): '73',
              ('Executive Subcommittee on Revenue', 'SEXC-SXRV'): '215',
              ('Executive', 'HEXC'): '211',
              ('Executive', 'SEXC'): '212',
              ('Expansion of Sex Offenses and Sex', 'HJUB-ESOR'): '216',
              ('Facilities Subcommittee', 'HHSV-FACI'): '217',
              ('Facilities Subcommittee', 'HHSV-HFAC'): '217',
              ('Facilities Subcommittee', 'HHSV-HFHS'): '217',
              ('Facilities and Institutions Subcomm', 'HHSV-FAIN'): '217',
              ('Family Law Subcommittee', 'HJUA-JFAL'): '1113',
              ('Fee For Service Initiatives', 'FFSI'): '220',
              ('Fee-For-Service Initiatives', 'HFEE'): '220',
              ('Fin Inst Subcommittee on Amendments', 'SFIC-FINA'): '222',
              ('Fin. Inst. Predatory Lending', 'SFIC-FIPL'): '223',
              ('Fin. Inst. Subcomm. Special Issues', 'SFIC-FISI'): '224',
              ('Finance Subcommittee', 'HREF-FINA'): '225',
              ('Finance Subcommittee', 'HREF-HREF'): '225',
              ('Finance', 'HREF-FINC'): '225',
              ('Financial Institutions', 'HFIN'): '228',
              ('Financial Institutions', 'SFIC'): '229',
              ('Fire & Emergency Services', 'HFES'): '230',
              ('Fire Protection', 'HFIR'): '231',
              ('Fire Service Subcommittee', 'HFES-FISE'): '232',
              ('Firearms Subcommittee', 'HAGC-FIRE'): '233',
              ('Firearms Subcommittee', 'HJUA-FIRE'): '234',
              ('Firearms and Firearm Safety Subcomm', 'HJUC-FIRE'): '235',
              ('Firearms and Firearm Safety Subcomm', 'HJUC-JCFF'): '235',
              ('Food Products Subcommittee', 'HAGC-FOOD'): '237',
              ('Force Fed Birds, Subcommittee', 'HAGC-HFEB'): '238',
              ('Foreclosure, Subcommittee of Local', 'HLGV-FORE'): '239',
              ('Future Roads: Growth & Improvement', 'HTRR-FRGI'): '240',
              ('Gaming Subcommittee', 'HEXC-GAME'): '243',
              ('Gaming', 'HGAM'): '241',
              ('Gaming', 'SGAM'): '242',
              ('Gaming-Revenue', 'SGRC'): '244',
              ('Gang Crimes, Judicary II Subcommitt', 'HJUB-HGCR'): '245',
              ('General Law Subcommittee', 'HJUA-GLAW'): '246',
              ('General Law Subcommittee', 'HJUA-HLAW'): '246',
              ('Gov. Accountability & Streamlining', 'HSGA-GOVE'): '248',
              ('Government Accountability/Pensions', 'SGAP'): '1101',
              ('Government Consolidation &  Modern', 'HGCM'): '249',
              ('Government Consolidation Analysis', 'HGCM-GCAC'): '279',
              ('Government Operations Subcommittee', 'HJUA-GOOP'): '250',
              ('Government Process Subcommittee', 'HSGA-HGPR'): '251',
              ('Government Reform', 'SGRM'): '252',
              ('Government Transparency', 'HGOT'): '253',
              ('Govt. Accountability and Streamlini', 'HSGA-GOAS'): '248',
              ('Growth, Reform & Fairness Subcommit', 'HREF-GRFS'): '255',
              ('HHS-BDD Subcommittee', 'SHHS-SHHB'): '256',
              ('HS Medicaid Subcommittee', 'HHSV-MEDI'): '257',
              ('Health & Healthcare Disparities', 'HHCD'): '258',
              ('Health & Human Services Health Care', 'SHHS-SHHH'): '259',
              ('Health & Human Services', 'SHHS'): '81',
              ('Health Care Availability  Access', 'HHCA'): '82',
              ('Health Care Availability & Access', 'HHCA'): '82',
              ('Health Care Licenses', 'HHCL'): '260',
              ('Health Exchange Marketplace Sub', 'HINS-HEMS'): '261',
              ('Health Exchanges Subcommittee', 'HINS-EXCH'): '261',
              ('Health Insurance Subcommittee', 'HINS-IHLT'): '1114',
              ('Healthy Illinois Plan', 'HHCA-HHIP'): '263',
              ('Higher Ed Special Issues Sub', 'HHED-HESI'): '264',
              ('Higher Ed. Subcommittee-Comm. Coll.', 'SCHE-HECC'): '265',
              ('Higher Education Analysis Subcommit', 'HHED-HEAS'): '268',
              ('Higher Education Issues Subcommitte', 'HHED-HEDI'): '264',
              ('Higher Education', 'HHED'): '266',
              ('Higher Education', 'SCHE'): '267',
              ('Highways & Transit Subcommittee', 'HTRR-HITR'): '270',
              ('Homeland Security & Emergency Prepa', 'HSEP'): '271',
              ('Hospital Closures, Subcommittee of', 'HAPH-HOSC'): '272',
              ('House Budget Oversight Panel', 'HBOP'): '273',
              ('Housing', 'HOUS'): '274',
              ('Housing & Community Affairs', 'SHCA'): '89',
              ('Housing & Urban Development', 'HHUD'): '90',
              ('Housing and Community Affairs', 'SHCA'): '89',
              ('Housing and Property Subcommittee', 'HJUA-HOPO'): '275',
              ('Housing and Urban Development', 'HHUD'): '90',
              ('Housing, Special Committee On', 'SSCH'): '280',
              ('Human Services', 'HHSV'): '276',
              ('Human Services', 'SHHS'): '81',
              ('Hunting Subcommittee', 'HAGC-HUNT'): '277',
              ('IL State Toll Highway Authority', 'TOLL'): '278',
              ('Income Tax Subcommittee', 'HREF-HTAX'): '93',
              ('Income Tax Subcommittee', 'HREF-INTX'): '93',
              ('Income Tax Subcommittee', 'HREF-ITAX'): '93',
              ('Income Tax Subcommittee', 'HREF-RITA'): '93',
              ('Income Tax', 'HREF-ITAX'): '93',
              ('Income Tax, Subcommittee on', 'HREV-ITAX'): '93',
              ('Income Tax, Subcommittee on', 'HREV-RITX'): '93',
              ('Informed Consent Subcommitee', 'HHSV-INFO'): '284',
              ('Informed Consent Subcommittee', 'HHSV-HICO'): '284',
              ('Informed Consent Subcommittee', 'HHSV-INCO'): '284',
              ('Informed Consent Subcommittee', 'HHSV-HCON'): '284',
              ('Infrastructure', 'HIND'): '286',
              ('Ins. Health Care Cost Drivers, Sub', 'HINS-COST'): '287',
              ('Ins. Subcommittee on Mandate Review', 'SINS-ISMR'): '288',
              ('Insurance & Pensions', 'SINS'): '95',
              ('Insurance', 'HINS'): '94',
              ('Insurance', 'SINS'): '95',
              ('Insurance: Health & Life', 'HINS'): '94',
              ('Insurance: Property & Casualty', 'HIPC'): '289',
              ('Intermodal Infrastructure', 'HINI'): '290',
              ('International Trade & Commerce', 'HITC'): '291',
              ('Job Growth, Preservation and Traini', 'HLBR-LJGP'): '1115',
              ('Joint Comm. on Government Reform', 'HJGR'): '292',
              ('Joint Comm. on Government Reform', 'SCGR'): '293',
              ('Joint Committee on MPEA', 'SMPE'): '294',
              ('Joint Committee on Pier', 'PIER'): '295',
              ('Joint Criminal Justice Reform Comm.', 'HCJR'): '296',
              ('Joint Criminal Justice Reform Comm.', 'SCJR'): '297',
              ('Joint Task Force I & R', 'JTIR'): '298',
              ('Jt. Task Force -- Rural Healthcare', 'TFRH'): '299',
              ('Jud. Criminal - Special Issues', 'SJCR-SJSI'): '300',
              ('Judicial Process Subcommittee', 'HJUA-JUDP'): '301',
              ('Judiciary - Civil', 'HJUA'): '7',
              ('Judiciary - Criminal', 'HJUC'): '302',
              ('Judiciary Civil Law', 'SJUD'): '8',
              ('Judiciary Criminal Law', 'SJCR'): '303',
              ('Judiciary I - Civil Law', 'HJUA'): '7',
              ('Judiciary II - Criminal Law', 'HJUB'): '304',
              ('Judiciary', 'HJUA'): '7',
              ('Judiciary', 'SJUD'): '8',
              ('Justice System Subcommittee', 'HMEH-JUST'): '305',
              ('Juvenile Justice & System-Involved', 'HJJS'): '306',
              ('Juvenile Justice Reform', 'HJJR'): '307',
              ('Juvenile Justice and System Involve', 'HJUC-JUVE'): '308',
              ('KidCare Subcommittee', 'HHSV-HKID'): '309',
              ('Labor & Commerce Committee', 'HLBR'): '55',
              ('Labor & Commerce', 'SCED'): '64',
              ('Labor & Commerce', 'HLBR'): '55',
              ('Labor and Commerce', 'SLAB'): '71',
              ('Labor', 'HLBR'): '55',
              ('Labor', 'SLAB'): '71',
              ('LaborSubcommittee on Special Issues', 'SLAB-SLSI'): '19',
              ('Land and Solid Waste, Subcom', 'HENE-LAND'): '310',
              ('Least Cost Power Procurement', 'HPOW'): '311',
              ('Legislative Petitions', 'SCLP'): '312',
              ('Legislative Review, Subcommittee', 'HEXC-LEGI'): '313',
              ('Licensed Activities and Pensions', 'SLIC'): '20',
              ('Licensed Activities', 'SLIC'): '20',
              ('Licenses and Registration, Subcommi', 'HTRN-LICN'): '22',
              ('Licenses, Subcommittee on', 'HTRN-LICN'): '22',
              ('Licensure Review Subcommittee', 'HBOL-LICR'): '314',
              ('Licensure Review', 'HHCL-LICR'): '23',
              ('Licensures Review Subcommittee', 'HHCL-LICE'): '23',
              ('Local Government Administration Sub', 'HCOT-LOCG'): '317',
              ('Local Government Consolidation Sub', 'HCOT-CTLG'): '318',
              ('Local Government Efficiency Subcomm', 'HCOT-HLGE'): '319',
              ('Local Government Subcommittee', 'HCOT-CTLC'): '1106',
              ('Local Government Subcommittee', 'HCIV-CLOC'): '27',
              ('Local Government Subcommittee', 'HCIV-HLOG'): '27',
              ('Local Government Subcommittee', 'HCIV-LOGO'): '27',
              ('Local Government Subcommittee', 'HCIV-LOGV'): '27',
              ('Local Government', 'HLGV'): '315',
              ('Local Government', 'SLGV'): '316',
              ('Local Retirement System Subcommitte', 'HPPN-PLRS'): '1116',
              ('Long Term Care Subcommittee', 'HINS-LTCI'): '321',
              ('Managing Sex Offender Issues, Subco', 'HJUB-MSOI'): '322',
              ('Mandate Subcommittee', 'HELM-MANS'): '323',
              ('Mandates Subcommittee', 'SINS-SINM'): '28',
              ('Mandates of the Elementary & Sec Ed', 'HELM-MAND'): '323',
              ('Mandatory Insurance, Subcommittee', 'HINS-MAND'): '325',
              ('Mass Transit Compliance, Subcom', 'HTRN-MASS'): '327',
              ('Mass Transit for Northeastern IL', 'SMTN'): '328',
              ('Mass Transit', 'HMAS'): '326',
              ('Med. Discipline/Ins./MalpracticeRef', 'SJUD-SMED'): '329',
              ('Medicaid Managed Care T F', 'MMTF'): '330',
              ('Medicaid Reform Committee', 'HSMR'): '331',
              ('Medicaid Reform Subcommittee', 'HHCA-MEDI'): '332',
              ('Medicaid Reform, Family & Children', 'HMRF'): '333',
              ('Medicaid Subcommittee', 'HAPH-MEDI'): '334',
              ('Medicaid Subcommittee', 'HHSV-HMED'): '1117',
              ('Mental Health', 'HMEH'): '335',
              ('Methamphetamine, Judiciary II Subco', 'HJUB-METH'): '336',
              ('Mineral Rights, Judiciary I-Civil L', 'HJUA-HJMR'): '337',
              ('Mineral and Surface Rights Issues', 'HJUA-MSRI'): '338',
              ('Minority Procurement', 'HSGA-MPRO'): '339',
              ('Minority/Disadvantage Analysis Subc', 'HLBR-LMDA'): '1118',
              ('Mobile Home T.F.', 'MHTF'): '340',
              ('Mobile Home T.F.', 'SMHT'): '340',
              ('Motor Fuel Analysis Subcommittee', 'HTRR-MOFA'): '342',
              ('Motorcycles/Trucking, Subcom', 'HTRN-MOTO'): '343',
              ('Museums, Arts, & Cultural Enhanceme', 'HMAC'): '344',
              ('Negotiations Subcommittee', 'HAGC-NEGO'): '345',
              ('Negotiations Subcommittee', 'HHCL-HNEG'): '346',
              ('Negotiations Subcommittee', 'HHCL-NEGO'): '346',
              ('New State Programs or Expenditures', 'HSGA-NEWS'): '347',
              ('No Child Left Behind Act of 2001', 'SESE-SECL'): '36',
              ('Oversight Medicaid Mang. Care', 'SOMM'): '30',
              ('Oversight Medicaid Mang. Care, Spec', 'SOMM'): '44',
              ('Paratransit, Subcommittee on', 'HMAS-PARA'): '349',
              ('Pay Day Loans, Subcommittee', 'HFIN-PDAY'): '350',
              ('Payday and Title Loans, Subcommitte', 'HFIN-LOAN'): '351',
              ('Penalty Enhancements and Enlargemen', 'HJUB-HPEG'): '352',
              ('Pension Benefits Review', 'SPAI-SPBR'): '0',
              ('Pension Fund Management Procurement', 'PFMP'): '353',
              ('Pension Funds Management', 'HPFM'): '354',
              ('Pension Investments', 'PENI'): '355',
              ('Pensions & Investments', 'SPAI'): '39',
              ('Pensions Subcommittee', 'SINS-SINP'): '356',
              ('Pensions and Investments', 'SPAI'): '39',
              ('Personnel & Pensions', 'HPPN'): '357',
              ('Personnel Code Subcommittee', 'HPPN-PPPC'): '1120',
              ('Petroleum Regulation Subcommittee', 'HAGC-PETR'): '365',
              ('Police & First Responders', 'HPFR'): '358',
              ('Police and Fire Pension Reform', 'HPPN-PFPR'): '359',
              ('Practice Acts Subcommittee', 'HHCL-HPAC'): '360',
              ('Prescription Drug Affordability', 'HPDA'): '1121',
              ('Prevailing Wage Subcommittee', 'HLBR-WAGE'): '361',
              ('Prison Reform', 'HPRF'): '362',
              ('Procedures Subcommittee', 'HSGA-PROC'): '363',
              ('Procurement', 'SCOP'): '364',
              ('Property Tax Reform', 'SREV-SRPT'): '43',
              ('Property Tax Subcommittee', 'HREF-HPRP'): '42',
              ('Property Tax Subcommittee', 'HREF-PROP'): '42',
              ('Property Tax Subcommittee', 'HREF-PTAX'): '42',
              ('Property Tax Subcommittee', 'HREF-RPTA'): '42',
              ('Property Tax', 'HREF-PTAX'): '42',
              ('Property Tax, Subcommittee on', 'HREV-PTAX'): '42',
              ('Property Tax, Subcommittee on', 'HREV-RPTX'): '42',
              ('Pub. High. Ed. Adm. Cost. Tui. Fees', 'SCHE-SPHE'): '368',
              ('Public Benefits Subcommittee', 'HHSV-HPBE'): '46',
              ('Public Benefits Subcommittee', 'HHSV-PUBL'): '46',
              ('Public Benefits Subcommittee', 'HHSV-PUBT'): '46',
              ('Public Benefits Subcommittee', 'HHSV-HPBH'): '46',
              ('Public Health Subcommittee', 'HCON-PUHE'): '371',
              ('Public Health', 'SPHL'): '370',
              ('Public Pension Investments', 'SPPI'): '372',
              ('Public Pensions & State Investments', 'SCPP'): '373',
              ('Public Policy & Accountability', 'HPPA'): '374',
              ('Public Private Partnerships', 'HPPP'): '375',
              ('Public Safety', 'HJUB-SAFE'): '376',
              ('Public Safety: Police & Fire Commit', 'HSPF'): '377',
              ('Public Utilities Cellular Service', 'HPUB-CELL'): '379',
              ('Public Utilities Subcommittee', 'HPUB-PUBL'): '380',
              ('Public Utilities', 'HPUB'): '378',
              ('Qualifications Challenge Committee', 'HQCC'): '381',
              ('Railroad Industry', 'HRRI'): '382',
              ('Railroad Safety', 'HRRS'): '383',
              ('Railroad and Air Transportation Sub', 'HTRR-RAIL'): '384',
              ('Railroads, Ports and Aviation Subco', 'HTRR-RPAV'): '385',
              ('Railroads, Subcommittee on', 'HTRN-RAIL'): '386',
              ('Rapid Growth District & Special Ed.', 'HELM-HRGD'): '387',
              ('Real & Personal Property Law Subcom', 'HJUA-RPPL'): '388',
              ('Real Estate, Prop. Probate & Trust', 'HJUA-HRPP'): '389',
              ('Real Estate, Property, Probate, Tru', 'HJUA-RPPT'): '390',
              ('Red Light Camera Subcommittee', 'HVES-REDL'): '391',
              ('Red Light', 'HVES-HRED'): '391',
              ('Redistricting', 'DIST'): '393',
              ('Redistricting', 'SRED'): '394',
              ('Regional Equity, Mass Transit Subco', 'HMAS-REGL'): '395',
              ('Registration & Regulation', 'HREG'): '396',
              ('Regulatory Matters Subcommittee', 'HPUB-REGU'): '410',
              ('Renewable Energy & Sustainability', 'HRES'): '398',
              ('Renewable Energy', 'HRNE'): '397',
              ('Residential Renters Rights & Respon', 'HHUD-RENT'): '399',
              ('Residential Services for Persons', 'HFEE-RSPM'): '400',
              ('Resources and Management Subcommitt', 'HENG-RESO'): '401',
              ('Restorative Justice', 'HREJ'): '402',
              ('Revenue & Finance', 'HREF'): '403',
              ('Revenue & Spending Subcommittee', 'HCOT-SPEN'): '406',
              ('Revenue Subcomm. on Special Issues', 'SREV-SRSI'): '65',
              ('Revenue Subcommittee on Amendments', 'SREV-SRAM'): '66',
              ('Revenue Subcommittee on Prop. Taxes', 'SREV-SRPT'): '43',
              ('Revenue Subcommittee-Amendments', 'SREV-SRAM'): '66',
              ('Revenue', 'HREV'): '403',
              ('Revenue', 'SREV'): '404',
              ('Review Subcommittee', 'SINS-SINR'): '407',
              ('Revnue Subcommittee  Special Issues', 'SREV-SRSI'): '65',
              ('Roads, Bridges & Traffic Safety', 'HTRN-ROAD'): '67',
              ('Roads, Bridges and Traffic Safety', 'HTRN-ROAD'): '67',
              ('Rules', 'HRUL'): '408',
              ('Rules', 'SCOA'): '21',
              ('Rural Economic Development', 'HRED'): '409',
              ('Sales & Other Tax, Subcommittee on', 'HREV-RSOT'): '70',
              ('Sales and Other Taxes Subcommittee', 'HREF-HSLE'): '70',
              ('Sales and Other Taxes Subcommittee', 'HREF-SALE'): '70',
              ('Sales and Other Taxes Subcommittee', 'HREF-STAX'): '70',
              ('Sales and Other Taxes', 'HREF-STAX'): '70',
              ('Sales and Other Taxes, Subcommittee', 'HREV-STAX'): '70',
              ('Sales, Amusement & Other Taxes', 'HREF-RSAT'): '70',
              ('Scholarship Tax Credit Oversight', 'HREF-STCO'): '72',
              ('School Buses Subcommittee', 'HVES-BUSE'): '412',
              ('School Code Waivers, Subcommittee', 'HELM-SCWA'): '413',
              ('School Transportation', 'HELM-STRN'): '414',
              ('Science, Technology, Engineering,', 'HELM-STEM'): '415',
              ('Select Committee on Discipline', 'HSCD'): '416',
              ('Sen. Comm. Whole', 'SCWL'): '35',
              ('Sen. T.F. on IL Alcoholic Bev. La', 'SIAB'): '417',
              ('Senate Committee of the Whole', 'SCWL'): '35',
              ('Senate Education Funding Reform', 'SEFR'): '418',
              ('Senior and Veterans Housing Sustain', 'HECD-SVHS'): '419',
              ('Sentencing, Penalties and Criminal', 'HJUC-SPCP'): '420',
              ('Sentencing, Penalties, and Criminal', 'HJUC-CPCP'): '421',
              ('Sex Crime Subcommittee', 'HJUB-SEXC'): '422',
              ('Sex Offenses Subcommittee', 'HJUA-SEOF'): '423',
              ('Sex Offenses and Sex Offender Regis', 'HJUC-SORE'): '424',
              ('Sex Offenses and Sex Offender Regis', 'HJUC-SOSO'): '424',
              ('Single Family Homeownership Stabili', 'HECD-SFHS'): '426',
              ('Sm Bus Empowerment Wkforce Develop', 'HSBE'): '76',
              ('Small Business Empowerment & Workfo', 'HSBE'): '76',
              ('Smart Growth & Regional Planning', 'HSGR'): '427',
              ('Social Change Subcommittee', 'HREJ-SOCH'): '428',
              ('Solid Waste Subcommittee', 'HENE-SSSW'): '429',
              ('Solid Waste', 'HENE-SWAS'): '429',
              ('Spec Committee on Education  Reform', 'SCER'): '431',
              ('Spec.Comm. on Impeachment Procedure', 'SITP'): '433',
              ('Special Bills Subcommittee', 'HSGA-HSPB'): '434',
              ('Special Budget Subcommittee', 'HAPG-SPBU'): '435',
              ('Special Comm. on Medicaid Reform', 'SCMR'): '436',
              ('Special Comm. on Watercraft Safety', 'SCWS'): '437',
              ('Special Investigating Committee', 'SPIC'): '438',
              ('Special Investigative Committee', 'HSIC'): '439',
              ('Special Issues Subcommittee', 'HAPE-APES'): '1103',
              ('Special Issues Subcommittee', 'HELM-HSPI'): '440',
              ('Special Issues Subcommittee', 'HELM-ISSU'): '440',
              ('Special Issues Subcommittee', 'HELM-SPEC'): '440',
              ('SPECIAL Issues Subcommittee', 'HELM-SPEC'): '440',
              ('Special Issues Subcommittee', 'HELO-ISSU'): '443',
              ('Special Issues- Subcommittee', 'HVES-TVSI'): '458',
              ('Special Issues Subcommittee', 'HELO-ESSI'): '443',
              ('Special Issues Subcommittee', 'HELM-ESSI'): '440',
              ('Special Issues Subcommittee', 'HVES-TSPI'): '458',
              ('Special License Plate Subcomittee', 'HSGA-LICN'): '444',
              ('Special License Plates Subcommittee', 'HVES-SLPD'): '445',
              ('Special License Plates, Subcommitte', 'HSGA-HSLP'): '446',
              ('Special Matters Subcommittee', 'HPUB-MATT'): '447',
              ('Special Matters Subcommittee', 'HPUB-SPMA'): '447',
              ('Special Needs Services', 'HSNS'): '449',
              ('Special Subcommittee', 'HSGA-SPEC'): '450',
              ('Special Subcommittee', 'HINS-ISPC'): '1128',
              ('Special Vehicle License Plates, Sub', 'HSGA-VEHI'): '451',
              ('Speed Limits Subcommittee', 'HVES-SPED'): '452',
              ('St Govt Subcomm Spec Issues/Amends', 'SGOA-SGIA'): '453',
              ('St. Govt Subcommittee on Amendments', 'SGOA-SGSA'): '921',
              ('St. Govt Subcommittee on Finance', 'SGOA-SGSF'): '455',
              ('State & Pension Fund Invest, Spec.', 'SSPF'): '461',
              ('State Government & Veterans Affairs', 'SGOA'): '3',
              ('State Government Administration', 'HSGA'): '456',
              ('State Government Review', 'SGOA-SSGR'): '457',
              ('State Government Subcommittee', 'HSGA-SGAS'): '1000',
              ('State Government', 'SGOA'): '3',
              ('State Retirement System Subcommitte', 'HPPN-PSRS'): '1129',
              ('Sub Com State Univ Civil Serv Syst.', 'SCHE-HECS'): '459',
              ('Sub Com on CA Affecting the Jud', 'SJUD-SJCA'): '84',
              ('Sub on Community Youth Employment', 'SHHS-CYEM'): '460',
              ('Sub on Constitutional Amendments', 'SEXC-SECA'): '86',
              ('Sub on Constitutional Amendments', 'SEXC-SSCA'): '86',
              ('Sub on EPA 111(d) Requirements', 'SNVR-SECE'): '462',
              ('Sub on Economic Development', 'SGOA-SOED'): '463',
              ('Sub on Emerging Tech & Spec.Issues', 'SCOM-SCES'): '464',
              ('Sub on Governmental Operations', 'SEXC-SEGO'): '32',
              ('Sub on Governmental Operations', 'SEXC-SSGO'): '32',
              ('Sub on Hunting and Trapping', 'SAGR-SAHT'): '466',
              ('Sub on Ins Mandates & Ins Issues', 'SINS-SIMI'): '467',
              ('Sub on Issues Relating to DCFS', 'SHHS-SHDC'): '468',
              ('Sub on Issues Relating to DCFS', 'SHHS-SSDC'): '468',
              ('Sub on Mental Health Issues', 'SEXC-SEMH'): '470',
              ('Sub on Research & Academic Medicine', 'SCHE-HEAM'): '471',
              ('Sub on Transportation Innovation', 'STRN-STRI'): '472',
              ('Sub. Comm on Statutes of Limitation', 'SCCL-SCSL'): '473',
              ('Sub. Confined Animal Feeding Ops.', 'SAGR-SCFO'): '474',
              ('Sub. on Public Notif.Requirements', 'SLGV-SPNR'): '570',
              ('Sub. On The Const.and Redist Issues', 'SJUD-SCRI'): '475',
              ('Sub. Public Higher Edu. Exec. Comp.', 'SCHE-SPHC'): '476',
              ('Sub. on Auto Insurance Rates', 'SINS-SIAR'): '477',
              ('Sub. on Compensation and Benefits', 'SGOA-SCAB'): '511',
              ('Sub. on Consequences of Fed.Policy', 'SHHS-SHFP'): '478',
              ('Sub. on Constitutional Amendments', 'SEXC-EXCA'): '86',
              ('Sub. on Energy and Labor Policy', 'SEXC-SELP'): '480',
              ('Sub. on Financial Regulation', 'SFIC-SFSR'): '481',
              ('Sub. on Generation, Util, & Telecom', 'SENE-SEGU'): '482',
              ('Sub. on Utility Rate Regulations', 'SENE-SEUR'): '912',
              ('Sub. on Interscholastic Athletics', 'SESE-SEIA'): '483',
              ('Sub. on Issues Impacting IL Youth', 'SHHS-SIIY'): '484',
              ('Sub. on Police Professionalism', 'SEXC-SCPP'): '485',
              ('Sub. on Water Related Issue', 'SNVR-SEWI'): '486',
              ('Subcommittee on Business Entities', 'SJUD-SCBE'): '497',
              ('Subcommittee on Drycleaners', 'SNVR-SEDC'): '490',
              ('Subcommittee on Energy Innovation', 'SENE-SENI'): '913',
              ('Sub. on Wireless Emerg Tel. Safety', 'SGOA-SWET'): '487',
              ('Sub. on the Monetary Award Program', 'SCHE-SMAP'): '488',
              ('Sub.Ins.Mandates & Special Issues', 'SINS-SIIM'): '489',
              ('Sub.on Ins.Madates & Special Issues', 'SINS-SIMS'): '489',
              ('Subcom Competitiveness & Innovation', 'SCOM-SCCI'): '96',
              ('Subcomm Comm. Affairs', 'SHCA-SCAF'): '909',
              ('Subcomm on Civil Process Procedure', 'SJUD-SJPP'): '491',
              ('Subcomm on Health Care Licensing', 'SLIC-SLHL'): '492',
              ('Subcomm on Pension Enhancements', 'SPAI-SPPE'): '1',
              ('Subcomm on Property and Environment', 'SJUD-SJPN'): '493',
              ('Subcomm. Global Warming & Energy', 'SENV-SGWE'): '495',
              ('Subcomm. Waterfront Devel./Preserv.', 'SENV-SEWD'): '496',
              ('Subcomm. on Civil Process&Procedure', 'SJUD-SJCP'): '491',
              ('Subcomm. on Fertilizers & Chemicals', 'SAGR-SAFC'): '4',
              ('Subcomm. on Property & Environment', 'SJUD-SJPE'): '493',
              ('Subcomm. on Prscriptive  Authority', 'SLIC-SLPA'): '498',
              ('Subcomm.Medicaid &Provider Rate Ref', 'SHHS-SMPR'): '500',
              ('Subcomm.on Containing Costs/Tuition', 'SAPB-SCCT'): '501',
              ('Subcom. on Pension Consolidation', 'SLIC-SLPC'): '510',
              ('Subcomm.on Pension Enhancements', 'SPAI-SPBE'): '1',
              ('Subcommitte  Pension Benefit Review', 'SPAI-SPBR'): '0',
              ('Subcommittee - Nursing Home Care', 'SPHL-SPNH'): '502',
              ('Subcommittee Legis.Tuition Waivers', 'SEXC-SXTW'): '503',
              ('Subcommittee Traffic Safety', 'STRN-STTS'): '504',
              ('Subcommittee on Airports', 'STRN-STRA'): '901',
              ('Subcommittee on Amendments', 'SCCP-SCPA'): '12',
              ('Subcommittee on Amendments', 'SJUD-SJDA'): '505',
              ('Subcommittee on Amendments', 'SJUD-SJOA'): '505',
              ('Subcommittee on Amendments', 'SLGV-SLGA'): '507',
              ('Subcommittee on Amendments', 'SLIC-SLAA'): '508',
              ('Subcommittee on Amendments', 'SNVR-SNVA'): '509',
              ('Subcommittee on Amendments', 'SPHL-SPHA'): '16',
              ('Subcommittee on Amendments', 'SPHL-SPOA'): '16',
              ('Subcommittee on Amendments', 'SPHL-SPSA'): '16',
              ('Subcommittee on Amendments', 'SREV-SRVA'): '512',
              ('Subcommittee on Amendments', 'STRN-STAM'): '18',
              ('Subcommittee on Amtrak', 'STRN-STAK'): '903',
              ('Subcommittee on Animal Welfare', 'SAGR-SAAW'): '513',
              ('Subcommittee on Annexation', 'SLGV-SLGN'): '514',
              ('Subcommittee on Bail Reform', 'SCCL-SCBR'): '515',
              ('Subcommittee on CLEAR Compliance', 'SCCL-SCCC'): '516',
              ('Subcommittee on CLEAR Compliance', 'SCCL-SCCL'): '516',
              ('Subcommittee on CLEAR Compliance', 'SCCL-SCLR'): '516',
              ('Subcommittee on Campaign Finance', 'SEXC-SECF'): '519',
              ('Subcommittee on Capital (AP)', 'SAPB-SACP'): '1100',
              ('Subcommittee on Capital (TR)', 'STRN-STOC'): '1102',
              ('Subcommittee on Charter Schools', 'SESE-SBCS'): '520',
              ('Subcommittee on Charter Schools', 'SESE-SECS'): '520',
              ('Subcommittee on Charter Schools', 'SESE-SSCR'): '520',
              ('Subcommittee on Civil Rights', 'SEXC-SECR'): '25',
              ('Subcommittee on Civil Rights', 'SEXC-SSCR'): '25',
              ('Subcommittee on Civil Rights', 'SEXC-SXCR'): '25',
              ('Subcommittee on Civil Rights', 'SJUD-SJCR'): '522',
              ('Subcommittee on Climate Change', 'SENV-SENC'): '26',
              ('Subcommittee on Coal Mining', 'SAGR-SACM'): '523',
              ('Subcommittee on Consolidation', 'SLGV-SLCC'): '524',
              ('Subcommittee on Const. Amendments', 'SEXC-SECA'): '86',
              ('Subcommittee on Const. Amendments', 'SEXC-SXCA'): '86',
              ('Subcommittee on Consumer Protection', 'SCOM-SCCP'): '914',
              ('Subcommittee on Court Fees & Fines', 'SJUD-SCFF'): '525',
              ('Subcommittee on Cryptocurrencies', 'SREV-SCCC'): '527',
              ('Subcommittee on Cybersecurity', 'STIT-STIC'): '526',
              ('Subcommittee on Deregulation', 'SENV-SEND'): '905',
              ('Subcommittee on Education', 'SEXC-EXED'): '73',
              ('Subcommittee on Election Law', 'SEXC-SBEL'): '29',
              ('Subcommittee on Election Law', 'SEXC-SEEL'): '29',
              ('Subcommittee on Election Law', 'SEXC-SSEL'): '29',
              ('Subcommittee on Election Reform', 'SELC-SEER'): '529',
              ('Subcommittee on Employment Issues', 'SLAB-SLEI'): '530',
              ('Subcommittee on Ethics', 'SEXC-SXET'): '930',
              ('Subcommittee on Federal Taxes', 'SREV-SCFT'): '194',
              ('Subcommittee on Firearms (CL)', 'SCCL-SCFA'): '168',
              ('Subcommittee on Firearms (JU)', 'SJUD-SSFA'): '531',
              ('Subcommittee on Firearms', 'SJUD-SJFA'): '531',
              ('Subcommittee on Firearms', 'SJUD-SJSF'): '531',
              ('Subcommittee on Food Labeling', 'SAGR-SAFL'): '900',
              ('Subcommittee on Fracking', 'SNVR-SESF'): '31',
              ('Subcommittee on Gaming Activities', 'SGAM-SGGA'): '537',
              ('Subcommittee on Gaming', 'SEXC-SEOG'): '210',
              ('Subcommittee on Gaming', 'SEXC-SESG'): '210',
              ('Subcommittee on Gaming', 'SEXC-SSGA'): '210',
              ('Subcommittee on Gov. Operations', 'SEXC-SEGO'): '32',
              ('Subcommittee on Health Exchanges', 'SINS-SIHE'): '538',
              ('Subcommittee on Housing', 'SHCA-SCHO'): '539',
              ('Subcommittee on Immunization', 'SPHL-SPOI'): '540',
              ('Subcommittee on Immunizations', 'SPHL-PSOI'): '540',
              ('Subcommittee on Income Taxes', 'SREV-SRIT'): '541',
              ('Subcommittee on Information Sharing', 'SREV-SSIS'): '542',
              ('Subcommittee on Insurance Mandates', 'SINS-SCIM'): '28',
              ('Subcommittee on Insurance Mandates', 'SINS-SINM'): '28',
              ('Subcommittee on Lic.Professionals', 'SLIC-SLLP'): '544',
              ('Subcommittee on Long Term Care', 'SPHL-SPLT'): '545',
              ('Subcommittee on Mandates', 'SESE-SEDM'): '546',
              ('Subcommittee on Medicaid', 'SHHS-SHHM'): '547',
              ('Subcommittee on Mortgages', 'SFIC-SFMG'): '548',
              ('Subcommittee on NCLB', 'SESE-NLCB'): '36',
              ('Subcommittee on Natural Resources', 'SENE-SENR'): '37',
              ('Subcommittee on New Districts', 'SLGV-SGND'): '550',
              ('Subcommittee on Payday Loan Reform', 'SFIC-SFPL'): '38',
              ('Subcommittee on Payday Loans', 'SFIC-SFPD'): '38',
              ('Subcommittee on Pension Reform', 'SPAI-SPPR'): '551',
              ('Subcommittee on Pension Reforms', 'SPAI-SPIP'): '551',
              ('Subcommittee on Pensions', 'SEXC-SEPE'): '553',
              ('Subcommittee on Prison Operation', 'SGOA-SCPO'): '554',
              ('Subcommittee on Procedures', 'SLGV-SLGP'): '555',
              ('Subcommittee on Procurement', 'SEXC-SESP'): '556',
              ('Subcommittee on Procurement', 'SEXC-SSOP'): '556',
              ('Subcommittee on Program Expansions', 'SCHE-SHPE'): '558',
              ('Subcommittee on Property Tax', 'SREV-SRPT'): '43',
              ('Subcommittee on Property Tax', 'SREV-SUPT'): '43',
              ('Subcommittee on Property Taxes', 'SREV-SRPR'): '43',
              ('Subcommittee on Property Taxes', 'SREV-SRPT'): '43',
              ('Subcommittee on Public Safety', 'SLGV-SLPS'): '561',
              ('Subcommittee on Railroad Safety', 'STRN-SRRS'): '562',
              ('Subcommittee on Readiness', 'SENE-SENR'): '908',
              ('Subcommittee on Red Light Cameras', 'STRN-SRLC'): '563',
              ('Subcommittee on Redistricting I', 'SRED-RRDI'): '564',
              ('Subcommittee on Redistricting II', 'SRED-RRII'): '565',
              ('Subcommittee on Regulatory Reform', 'SEXC-SERR'): '45',
              ('Subcommittee on Resolutions', 'SGOA-SSUR'): '566',
              ('Subcommittee on Restorative Justice', 'SEXC-SERJ'): '910',
              ('Subcommittee on Sales Taxes', 'SREV-SRST'): '567',
              ('Subcommittee on Special Issues (AP)', 'SAPB-SASI'): '571',
              ('Subcommittee on Special Issues (CE)', 'SCED-SCSI'): '572',
              ('Subcommittee on Special Issues (CL)', 'SCCL-SCLS'): '69',
              ('Subcommittee on Special Issues (CL)', 'SCCL-SCSI'): '69',
              ('Subcommittee on Special Issues (CL)', 'SCCL-SSSI'): '69',
              ('Subcommittee on Special Issues (EC)', 'SNVR-SESI'): '587',
              ('Subcommittee on Special Issues (ED)', 'SESE-SBSI'): '48',
              ('Subcommittee on Special Issues (ED)', 'SESE-SESI'): '48',
              ('Subcommittee on Special Issues (ED)', 'SESE-SSSI'): '48',
              ('Subcommittee on Special Issues (EN)', 'SENE-SESI'): '57',
              ('Subcommittee on Special Issues (EX)', 'SEXC-SESI'): '58',
              ('Subcommittee on Special Issues (EX)', 'SEXC-SSSI'): '58',
              ('Subcommittee on Special Issues (GR)', 'SGRM-SGRS'): '577',
              ('Subcommittee on Special Issues (HS)', 'SHHS-HSSI'): '578',
              ('Subcommittee on Special Issues (HS)', 'SHHS-SSSI'): '578',
              ('Subcommittee on Special Issues (IN)', 'SINS-SISI'): '580',
              ('Subcommittee on Special Issues (JU)', 'SJUD-SSSI'): '581',
              ('Subcommittee on Special Issues (LA)', 'SLAB-SLAS'): '19',
              ('Subcommittee on Special Issues (LA)', 'SLIC-LASI'): '51',
              ('Subcommittee on Special Issues (LA)', 'SLIC-SLSI'): '51',
              ('Subcommittee on Special Issues (LB)', 'SLAB-SLSI'): '19',
              ('Subcommittee on Special Issues (LC)', 'SLAB-SLSI'): '19',
              ('Subcommittee on Special Issues (LG)', 'SLGV-SLCS'): '13',
              ('Subcommittee on Special Issues (LG)', 'SLGV-SLGS'): '13',
              ('Subcommittee on Special Issues (LG)', 'SLGV-SLSI'): '13',
              ('Subcommittee on Special Issues (PH)', 'SPHL-SPHI'): '17',
              ('Subcommittee on Special Issues (PH)', 'SPHL-SPSI'): '17',
              ('Subcommittee on Special Issues (RV)', 'SREV-SRSI'): '65',
              ('Subcommittee on Special Issues (RV)', 'SREV-SSSI'): '65',
              ('Subcommittee on Special Issues (SE)', 'SENE-SESI'): '57',
              ('Subcommittee on Special Issues (SG)', 'SGOA-SGSI'): '585',
              ('Subcommittee on Special Issues (SG)', 'SGOA-SOSI'): '585',
              ('Subcommittee on Special Issues (SN)', 'SNVR-SNSI'): '587',
              ('Subcommittee on Special Issues (ST)', 'STRN-STSI'): '74',
              ('Subcommittee on Special Issues (TR)', 'STRN-STSI'): '74',
              ('Subcommittee on Special Issues (TR)', 'STRN-STTI'): '74',
              ('Subcommittee on Special Issues', 'SCCL-SCSI'): '69',
              ('Subcommittee on Special Issues', 'SCCP-SCPI'): '1002',
              ('Subcommittee on Special Issues', 'SESE-SESI'): '48',
              ('Subcommittee on Special Issues', 'SEXC-SXSI'): '568',
              ('Subcommittee on Special Issues', 'SHHS-SHSI'): '569',
              ('Subcommittee on Special Issues', 'SLAB-SLAI'): '19',
              ('Subcommittee on Special Issues', 'SLIC-SLSI'): '51',
              ('Subcommittee on Special Issues', 'SLIC-SLSS'): '51',
              ('Subcommittee on Special Issues', 'SPHL-SPHS'): '17',
              ('Subcommittee on Special Issues', 'SPHL-SPSI'): '17',
              ('Subcommittee on Special Issues', 'SREV-SRSI'): '65',
              ('Subcommittee on Special Issues', 'SREV-SRVS'): '65',
              ('Subcommittee on St. Gov Operations', 'SEXC-SESG'): '589',
              ('Subcommittee on State & Local Govt.', 'SEXC-SXLG'): '206',
              ('Subcommittee on State Designations', 'SGOA-SGSD'): '591',
              ('Subcommittee on State Regulation', 'SGAM-SGSR'): '592',
              ('Subcommittee on Tax Credits', 'SREV-SRTC'): '593',
              ('Subcommittee on Tax Credits', 'SREV-SSTC'): '593',
              ('Subcommittee on Tollways', 'STRN-STOL'): '595',
              ('Subcommittee on Tort Reform', 'SJUD-SJTR'): '596',
              ('Subcommittee on Tourism', 'SREV-SRTM'): '597',
              ('Subcommittee on Transparency', 'SENE-SENT'): '598',
              ('Substance Abuse Special', 'HSSA'): '599',
              ('Substance Abuse Subcommittee', 'HMEH-ABUS'): '600',
              ('Supplier Diversity, Special Com. On', 'SCSD'): '623',
              ('Tax Policy: Business Climate Sub', 'HREF-TAXB'): '601',
              ('Tax Policy: Business Climate Sub', 'HSGA-TAXB'): '602',
              ('Tax Policy: Income Tax Subcommittee', 'HSGA-TAXI'): '603',
              ('Tax Policy: Other Taxes Subcommitte', 'HREF-TAXO'): '604',
              ('Tax Policy: Other Taxes Subcommitte', 'HSGA-TAXO'): '605',
              ('Tax Policy: Sales Tax Subcommittee', 'HREF-TASA'): '606',
              ('Tax Policy: Sales Tax Subcommittee', 'HSGA-TAXS'): '607',
              ('Tax Sales Subcommittee', 'HREF-TAXS'): '608',
              ('Taxi Policy: Income Tax Subcommitte', 'HREF-TAXI'): '1003',
              ('Telecommunications & InfoTechnology', 'STIT'): '610',
              ('Telecommunications & Technology', 'STEL'): '611',
              ('Telecommunications Committee', 'HTEL'): '75',
              ('Telecommunications', 'HTEL'): '75',
              ('Telecommunications, Subcommittee on', 'HPUB-TELE'): '612',
              ('Tollway Oversight Review Subcommitt', 'HTOL-TOLL'): '614',
              ('Tollway Oversight', 'HTOL'): '613',
              ('Tort Liability Law Subcommittee', 'HJUA-TLLS'): '615',
              ('Tort Liability Subcommittee', 'HJUA-JTOL'): '615',
              ('Tourism & Conventions', 'HTOR'): '77',
              ('Tourism', 'HTOR'): '77',
              ('Tourism, Hospitality & Craft Ind.', 'HTHC'): '616',
              ('Towing Oversight Subcommittee', 'HREF-HTOW'): '78',
              ('Towing Oversight Subcommittee', 'HREF-TOWO'): '78',
              ('Trans Subcommittee Special Issues', 'STRN-STSI'): '74',
              ('Trans. Regulation Accountability', 'HTRR-TRAS'): '79',
              ('Trans. Subcommittee on Amendments', 'STRN-STRA'): '11',
              ('Transit Management and Performance', 'HMAS-TMAP'): '617',
              ('Transit, Subcommittee on', 'HHUD-TRAN'): '618',
              ('Transparency Subcommittee', 'HCOT-TRAN'): '619',
              ('Transportation & Motor Vehicles', 'HTRN'): '621',
              ('Transportation Reg. and Reg. Subcom', 'HTRR-TRRS'): '622',
              ('Transportation Subcomm. Amendments', 'STRN-STRA'): '11',
              ('Transportation Subcomm. Spec. Issue', 'STRN-STSI'): '74',
              ('Transportation Subcommittee', 'HAPP-STRA'): '624',
              ('Transportation', 'STRN'): '620',
              ('Transportation, Regulation, Roads', 'HTRR'): '80',
              ('Transportation: License Plates Subc', 'HVES-HLPS'): '625',
              ('Transportation: License Plates', 'HVES-TRLP'): '625',
              ('Transportation: Railroad & Air Subc', 'HTRR-HRRA'): '384',
              ('Transportation: Railroad and Air', 'HTRR-TRAS'): '384',
              ('Transportation: Reg. & Reg. Sub.', 'HTRR-HRRS'): '622',
              ('Transportation: Regis and Regu', 'HTRR-TRES'): '622',
              ('Transportation: Regulation, Roads', 'HTRR'): '80',
              ('Transportation: Signs & Signals Sub', 'HVES-HSSS'): '630',
              ('Transportation: Signs', 'HVES-TRSI'): '630',
              ('Transportation: Vehicles & Safety', 'HVES'): '83',
              ('Trusts & Estates Law Subcommittee', 'HJUA-TELS'): '632',
              ('Unemployment Insurance Subcommittee', 'HLBR-HUIN'): '634',
              ('Unemployment Insurance Subcommittee', 'HLBR-UEMP'): '634',
              ('Unemployment Insurance Subcommittee', 'HLBR-UINS'): '634',
              ('Unemployment Insurance Subcommittee', 'HLBR-UNEM'): '634',
              ('Vehicles & Safety', 'HVES'): '83',
              ('Veterans Affairs', 'HVET'): '87',
              ('Veterans Affairs', 'SVET'): '637',
              ('Voter Education & Registration Sub', 'HELE-VERS'): '638',
              ('Wage Policy and Study Subcommittee', 'HLBR-LWPS'): '1131',
              ('Water Quality & Quantity, Subcom', 'HENE-WATR'): '88',
              ('Water Subcommittee', 'HENE-SWTR'): '88',
              ('Water', 'HENE-WATE'): '88',
              ('Welfare', 'SHHS-SHHW'): '640',
              ('Whole, Committee of the', 'HCWL'): '34',
              ('Workers Comp Unemploy Insurance', 'HLBR-WCUI'): '91',
              ('Workers Comp. and Unemployment Ins.', 'HLBR-WCUI'): '91',
              ('Workers Compensation Subcommittee', 'HLBR-HWCO'): '641',
              ('Workers Compensation Subcommittee', 'HLBR-WKCO'): '641',
              ('Workforce Development Subcommittee', 'HLBR-LWDS'): '1132',
              ('Workforce Reconciliation Subcommitt', 'HLBR-HWOR'): '40',
              ('Workforce Reconciliation Subcommitt', 'HLBR-WORE'): '40',
              ('Workforce Reconciliation Subcommitt', 'HLBR-WORK'): '40',
              ('Youth & Young Adults', 'HYYA'): '646',
              ('Youth and Family', 'HYOF'): '647'}
