metadata = dict(
    name='Wyoming',
    abbreviation='wy',
    legislature_name='Wyoming Legislature',
    upper_chamber_name='Senate',
    lower_chamber_name='House of Representatives',
    upper_chamber_title='Senator',
    lower_chamber_title='Representative',
    upper_chamber_term=4,
    lower_chamber_term=2,
    terms=[{'name': '2001 General Session',
            'start_year': 2001,
            'end_year': 2001,
            'sessions': ['2001']},
           {'name': '2002 Budget Session',
            'start_year': 2002,
            'end_year': 2002,
            'sessions': ['2002']},
           {'name': '2003 General Session',
            'start_year': 2003,
            'end_year': 2003,
            'sessions': ['2003']},
           {'name': '2004 Budget Session',
            'start_year': 2004,
            'end_year': 2004,
            'sessions': ['2004']},
           {'name': '2005 General Session',
            'start_year': 2005,
            'end_year': 2005,
            'sessions': ['2005']},
           {'name': '2006 Budget Session',
            'start_year': 2006,
            'end_year': 2006,
            'sessions': ['2006']},
           {'name': '2007 General Session',
            'start_year': 2007,
            'end_year': 2007,
            'sessions': ['2007']},
           {'name': '2008 Budget Session',
            'start_year': 2008,
            'end_year': 2008,
            'sessions': ['2008']},
           {'name': '2009 General Session',
            'start_year': 2009,
            'end_year': 2009,
            'sessions': ['2009']},
           {'name': '2010 Budget Session',
            'start_year': 2010,
            'end_year': 2010,
            'sessions': ['2011']},
           {'name': '2011 General Session',
            'start_year': 2011,
            'end_year': 2011,
            'sessions': ['2011']},
           ],
    session_details={'2001': {'type': 'general'},
                     '2002': {'type': 'budget'},
                     '2003': {'type': 'general'},
                     '2004': {'type': 'budget'},
                     '2005': {'type': 'general'},
                     '2006': {'type': 'budget'},
                     '2007': {'type': 'general'},
                     '2008': {'type': 'budget'},
                     '2009': {'type': 'general'},
                     '2010': {'type': 'budget'},
                     '2011': {'type': 'general'},
                     },
)
