metadata = dict(
    name='Wyoming',
    abbreviation='wy',
    legislature_name='Wyoming Legislature',
    upper_chamber_name='Senate',
    lower_chamber_name='House of Representatives',
    upper_chamber_title='Senator',
    lower_chamber_title='Representative',
    upper_chamber_term=4,
    lower_chamber_term=2,
    terms=[
           {'name': '56th',
            'start_year': 2001,
            'end_year': 2002,
            'sessions': ['2001 General Session', '2002 Budget Session']},
           {'name': '57th',
            'start_year': 2003,
            'end_year': 2004,
            'sessions': ['2003 General Session', '2004 Budget Session']},
           {'name': '58th',
            'start_year': 2005,
            'end_year': 2006,
            'sessions': ['2005 General Session', '2006 Budget Session']},
           {'name': '59th',
            'start_year': 2007,
            'end_year': 2008,
            'sessions': ['2007 General Session', '2008 Budget Session']},
           {'name': '60th',
            'start_year': 2009,
            'end_year': 2010,
            'sessions': ['2009 General Session', '2010 Budget Session']},
           {'name': '61st',
            'start_year': 2011,
            'end_year': 2012,
            'sessions': ['2011 General Session']},
           ],
    session_details={'2001 General Session': {'type': 'general'},
                     '2002 Budget Session': {'type': 'budget'},
                     '2003 General Session': {'type': 'general'},
                     '2004 Budget Session': {'type': 'budget'},
                     '2005 General Session': {'type': 'general'},
                     '2006 Budget Session': {'type': 'budget'},
                     '2007 General Session': {'type': 'general'},
                     '2008 Budget Session': {'type': 'budget'},
                     '2009 General Session': {'type': 'general'},
                     '2010 Budget Session': {'type': 'budget'},
                     '2011 General Session': {'type': 'general'},
                     },
)
