#!/bin/sh

python3 -m flake8 \
    openstates/ak \
    openstates/al \
    openstates/ar \
    openstates/az \
    openstates/ca \
    openstates/co \
    openstates/ct \
    openstates/dc \
    openstates/de \
    openstates/ct \
    openstates/fl \
    openstates/ga \
    openstates/hi \
    openstates/ia \
    openstates/id \
    openstates/in \
    openstates/ks \
    openstates/ky \
    openstates/la \
    openstates/md \
    openstates/me \
    openstates/mi \
    openstates/mn \
    openstates/mo \
    openstates/ms \
    openstates/mt \
    openstates/nc \
    openstates/nd \
    openstates/ne \
    openstates/nj \
    openstates/nm \
    openstates/nv \
    openstates/oh \
    openstates/ok \
    openstates/or \
    openstates/pa \
    openstates/ri \
    openstates/sc \
    openstates/sd \
    openstates/tn \
    openstates/ut \
    openstates/va \
    openstates/vt \
    openstates/wa \
    openstates/wi \
    openstates/wv \
    openstates/wy \
    openstates/utils \
    pupa2billy
