from pupa.scrape import Jurisdiction, Organization
# from .people import NHPersonScraper
# from .committees import NHCommitteeScraper
from .bills import NHBillScraper


class NewHampshire(Jurisdiction):
    division_id = "ocd-division/country:us/state:nh"
    classification = "government"
    name = "New Hampshire"
    url = "TODO"
    scrapers = {
        # 'people': NHPersonScraper,
        # 'committees': NHCommitteeScraper,
        'bills': NHBillScraper,
    }
    legislative_sessions = [
        {
            "_scraped_name": "2011 Session",
            "identifier": "2011",
            "name": "2011 Regular Session",
        },
        {
            "_scraped_name": "2012 Session",
            "identifier": "2012",
            "name": "2012 Regular Session",
        },
        {
            "_scraped_name": "2013",
            "identifier": "2013",
            "name": "2013 Regular Session",
        },
        {
            "_scraped_name": "2014 Session",
            "identifier": "2014",
            "name": "2014 Regular Session",
        },
        {
            "_scraped_name": "2015 Session",
            "identifier": "2015",
            "name": "2015 Regular Session",
        },
        {
            "_scraped_name": "2016 Session",
            "identifier": "2016",
            "name": "2016 Regular Session",
        },
        {
            "_scraped_name": "2017 Session",
            "identifier": "2017",
            "name": "2017 Regular Session",
            "start_date": "2017-01-04",
            "end_date": "2017-06-30",
        },
        {
            "_scraped_name": "2018 Session",
            "end_date": "2018-06-30",
            "identifier": "2018",
            "name": "2018 Regular Session",
            "start_date": "2018-01-03",
        },
    ]
    ignored_scraped_sessions = [
        "2013 Session",
        "2017 Session Bill Status Tables Link.txt"
    ]

    def get_organizations(self):
        legislature_name = "New Hampshire General Court"
        lower_chamber_name = "House"
        lower_title = "Representative"
        upper_chamber_name = "Senate"
        upper_title = "Senator"

        legislature = Organization(name=legislature_name,
                                   classification="legislature")
        upper = Organization(upper_chamber_name, classification='upper',
                             parent_id=legislature._id)
        lower = Organization(lower_chamber_name, classification='lower',
                             parent_id=legislature._id)

        for label, num, division_id in LOWER_DISTRICTS:
            lower.add_post(label=label, role=lower_title, division_id=division_id)

        for n in range(1, 25):
            upper.add_post(
                label=str(n), role=upper_title,
                division_id='{}/sldu:{}'.format(self.division_id, n))

        yield legislature
        yield upper
        yield lower

    def get_session_list(self):
        from openstates.utils import url_xpath
        zips = url_xpath('http://gencourt.state.nh.us/downloads/',
                         '//a[contains(@href, "Bill%20Status%20Tables")]/text()')
        return [zip.replace(' Bill Status Tables.zip', '') for zip in zips]


LOWER_DISTRICTS = [
    ("Belknap 1", 1, "ocd-division/country:us/state:nh/sldl:belknap_1"),
    ("Belknap 2", 4, "ocd-division/country:us/state:nh/sldl:belknap_2"),
    ("Belknap 3", 4, "ocd-division/country:us/state:nh/sldl:belknap_3"),
    ("Belknap 4", 2, "ocd-division/country:us/state:nh/sldl:belknap_4"),
    ("Belknap 5", 2, "ocd-division/country:us/state:nh/sldl:belknap_5"),
    ("Belknap 6", 2, "ocd-division/country:us/state:nh/sldl:belknap_6"),
    ("Belknap 7", 1, "ocd-division/country:us/state:nh/sldl:belknap_7"),
    ("Belknap 8", 1, "ocd-division/country:us/state:nh/sldl:belknap_8"),
    ("Belknap 9", 1, "ocd-division/country:us/state:nh/sldl:belknap_9"),
    ("Carroll 1", 1, "ocd-division/country:us/state:nh/sldl:carroll_1"),
    ("Carroll 2", 3, "ocd-division/country:us/state:nh/sldl:carroll_2"),
    ("Carroll 3", 2, "ocd-division/country:us/state:nh/sldl:carroll_3"),
    ("Carroll 4", 2, "ocd-division/country:us/state:nh/sldl:carroll_4"),
    ("Carroll 5", 3, "ocd-division/country:us/state:nh/sldl:carroll_5"),
    ("Carroll 6", 2, "ocd-division/country:us/state:nh/sldl:carroll_6"),
    ("Carroll 7", 1, "ocd-division/country:us/state:nh/sldl:carroll_7"),
    ("Carroll 8", 1, "ocd-division/country:us/state:nh/sldl:carroll_8"),
    ("Cheshire 1", 4, "ocd-division/country:us/state:nh/sldl:cheshire_1"),
    ("Cheshire 2", 1, "ocd-division/country:us/state:nh/sldl:cheshire_2"),
    ("Cheshire 3", 1, "ocd-division/country:us/state:nh/sldl:cheshire_3"),
    ("Cheshire 4", 1, "ocd-division/country:us/state:nh/sldl:cheshire_4"),
    ("Cheshire 5", 1, "ocd-division/country:us/state:nh/sldl:cheshire_5"),
    ("Cheshire 6", 1, "ocd-division/country:us/state:nh/sldl:cheshire_6"),
    ("Cheshire 7", 1, "ocd-division/country:us/state:nh/sldl:cheshire_7"),
    ("Cheshire 8", 1, "ocd-division/country:us/state:nh/sldl:cheshire_8"),
    ("Cheshire 9", 2, "ocd-division/country:us/state:nh/sldl:cheshire_9"),
    ("Cheshire 10", 1, "ocd-division/country:us/state:nh/sldl:cheshire_10"),
    ("Cheshire 11", 2, "ocd-division/country:us/state:nh/sldl:cheshire_11"),
    ("Cheshire 12", 2, "ocd-division/country:us/state:nh/sldl:cheshire_12"),
    ("Cheshire 13", 1, "ocd-division/country:us/state:nh/sldl:cheshire_13"),
    ("Cheshire 14", 1, "ocd-division/country:us/state:nh/sldl:cheshire_14"),
    ("Cheshire 15", 1, "ocd-division/country:us/state:nh/sldl:cheshire_15"),
    ("Cheshire 16", 2, "ocd-division/country:us/state:nh/sldl:cheshire_16"),
    ("Coos 1", 2, "ocd-division/country:us/state:nh/sldl:coos_1"),
    ("Coos 2", 1, "ocd-division/country:us/state:nh/sldl:coos_2"),
    ("Coos 3", 3, "ocd-division/country:us/state:nh/sldl:coos_3"),
    ("Coos 4", 1, "ocd-division/country:us/state:nh/sldl:coos_4"),
    ("Coos 5", 1, "ocd-division/country:us/state:nh/sldl:coos_5"),
    ("Coos 6", 1, "ocd-division/country:us/state:nh/sldl:coos_6"),
    ("Coos 7", 1, "ocd-division/country:us/state:nh/sldl:coos_7"),
    ("Grafton 1", 2, "ocd-division/country:us/state:nh/sldl:grafton_1"),
    ("Grafton 2", 1, "ocd-division/country:us/state:nh/sldl:grafton_2"),
    ("Grafton 3", 1, "ocd-division/country:us/state:nh/sldl:grafton_3"),
    ("Grafton 4", 1, "ocd-division/country:us/state:nh/sldl:grafton_4"),
    ("Grafton 5", 1, "ocd-division/country:us/state:nh/sldl:grafton_5"),
    ("Grafton 6", 1, "ocd-division/country:us/state:nh/sldl:grafton_6"),
    ("Grafton 7", 1, "ocd-division/country:us/state:nh/sldl:grafton_7"),
    ("Grafton 8", 3, "ocd-division/country:us/state:nh/sldl:grafton_8"),
    ("Grafton 9", 2, "ocd-division/country:us/state:nh/sldl:grafton_9"),
    ("Grafton 10", 1, "ocd-division/country:us/state:nh/sldl:grafton_10"),
    ("Grafton 11", 1, "ocd-division/country:us/state:nh/sldl:grafton_11"),
    ("Grafton 12", 4, "ocd-division/country:us/state:nh/sldl:grafton_12"),
    ("Grafton 13", 4, "ocd-division/country:us/state:nh/sldl:grafton_13"),
    ("Grafton 14", 1, "ocd-division/country:us/state:nh/sldl:grafton_14"),
    ("Grafton 15", 1, "ocd-division/country:us/state:nh/sldl:grafton_15"),
    ("Grafton 16", 1, "ocd-division/country:us/state:nh/sldl:grafton_16"),
    ("Grafton 17", 1, "ocd-division/country:us/state:nh/sldl:grafton_17"),
    ("Hillsborough 1", 2, "ocd-division/country:us/state:nh/sldl:hillsborough_1"),
    ("Hillsborough 2", 3, "ocd-division/country:us/state:nh/sldl:hillsborough_2"),
    ("Hillsborough 3", 1, "ocd-division/country:us/state:nh/sldl:hillsborough_3"),
    ("Hillsborough 4", 2, "ocd-division/country:us/state:nh/sldl:hillsborough_4"),
    ("Hillsborough 5", 2, "ocd-division/country:us/state:nh/sldl:hillsborough_5"),
    ("Hillsborough 6", 5, "ocd-division/country:us/state:nh/sldl:hillsborough_6"),
    ("Hillsborough 7", 6, "ocd-division/country:us/state:nh/sldl:hillsborough_7"),
    ("Hillsborough 8", 2, "ocd-division/country:us/state:nh/sldl:hillsborough_8"),
    ("Hillsborough 9", 2, "ocd-division/country:us/state:nh/sldl:hillsborough_9"),
    ("Hillsborough 10", 2, "ocd-division/country:us/state:nh/sldl:hillsborough_10"),
    ("Hillsborough 11", 2, "ocd-division/country:us/state:nh/sldl:hillsborough_11"),
    ("Hillsborough 12", 2, "ocd-division/country:us/state:nh/sldl:hillsborough_12"),
    ("Hillsborough 13", 2, "ocd-division/country:us/state:nh/sldl:hillsborough_13"),
    ("Hillsborough 14", 2, "ocd-division/country:us/state:nh/sldl:hillsborough_14"),
    ("Hillsborough 15", 2, "ocd-division/country:us/state:nh/sldl:hillsborough_15"),
    ("Hillsborough 16", 2, "ocd-division/country:us/state:nh/sldl:hillsborough_16"),
    ("Hillsborough 17", 2, "ocd-division/country:us/state:nh/sldl:hillsborough_17"),
    ("Hillsborough 18", 2, "ocd-division/country:us/state:nh/sldl:hillsborough_18"),
    ("Hillsborough 19", 2, "ocd-division/country:us/state:nh/sldl:hillsborough_19"),
    ("Hillsborough 20", 2, "ocd-division/country:us/state:nh/sldl:hillsborough_20"),
    ("Hillsborough 21", 8, "ocd-division/country:us/state:nh/sldl:hillsborough_21"),
    ("Hillsborough 22", 3, "ocd-division/country:us/state:nh/sldl:hillsborough_22"),
    ("Hillsborough 23", 4, "ocd-division/country:us/state:nh/sldl:hillsborough_23"),
    ("Hillsborough 24", 2, "ocd-division/country:us/state:nh/sldl:hillsborough_24"),
    ("Hillsborough 25", 2, "ocd-division/country:us/state:nh/sldl:hillsborough_25"),
    ("Hillsborough 26", 2, "ocd-division/country:us/state:nh/sldl:hillsborough_26"),
    ("Hillsborough 27", 2, "ocd-division/country:us/state:nh/sldl:hillsborough_27"),
    ("Hillsborough 28", 3, "ocd-division/country:us/state:nh/sldl:hillsborough_28"),
    ("Hillsborough 29", 3, "ocd-division/country:us/state:nh/sldl:hillsborough_29"),
    ("Hillsborough 30", 3, "ocd-division/country:us/state:nh/sldl:hillsborough_30"),
    ("Hillsborough 31", 3, "ocd-division/country:us/state:nh/sldl:hillsborough_31"),
    ("Hillsborough 32", 3, "ocd-division/country:us/state:nh/sldl:hillsborough_32"),
    ("Hillsborough 33", 3, "ocd-division/country:us/state:nh/sldl:hillsborough_33"),
    ("Hillsborough 34", 3, "ocd-division/country:us/state:nh/sldl:hillsborough_34"),
    ("Hillsborough 35", 3, "ocd-division/country:us/state:nh/sldl:hillsborough_35"),
    ("Hillsborough 36", 3, "ocd-division/country:us/state:nh/sldl:hillsborough_36"),
    ("Hillsborough 37", 11, "ocd-division/country:us/state:nh/sldl:hillsborough_37"),
    ("Hillsborough 38", 2, "ocd-division/country:us/state:nh/sldl:hillsborough_38"),
    ("Hillsborough 39", 1, "ocd-division/country:us/state:nh/sldl:hillsborough_39"),
    ("Hillsborough 40", 1, "ocd-division/country:us/state:nh/sldl:hillsborough_40"),
    ("Hillsborough 41", 1, "ocd-division/country:us/state:nh/sldl:hillsborough_41"),
    ("Hillsborough 42", 2, "ocd-division/country:us/state:nh/sldl:hillsborough_42"),
    ("Hillsborough 43", 3, "ocd-division/country:us/state:nh/sldl:hillsborough_43"),
    ("Hillsborough 44", 2, "ocd-division/country:us/state:nh/sldl:hillsborough_44"),
    ("Hillsborough 45", 2, "ocd-division/country:us/state:nh/sldl:hillsborough_45"),
    ("Merrimack 1", 1, "ocd-division/country:us/state:nh/sldl:merrimack_1"),
    ("Merrimack 2", 2, "ocd-division/country:us/state:nh/sldl:merrimack_2"),
    ("Merrimack 3", 2, "ocd-division/country:us/state:nh/sldl:merrimack_3"),
    ("Merrimack 4", 1, "ocd-division/country:us/state:nh/sldl:merrimack_4"),
    ("Merrimack 5", 2, "ocd-division/country:us/state:nh/sldl:merrimack_5"),
    ("Merrimack 6", 2, "ocd-division/country:us/state:nh/sldl:merrimack_6"),
    ("Merrimack 7", 1, "ocd-division/country:us/state:nh/sldl:merrimack_7"),
    ("Merrimack 8", 1, "ocd-division/country:us/state:nh/sldl:merrimack_8"),
    ("Merrimack 9", 2, "ocd-division/country:us/state:nh/sldl:merrimack_9"),
    ("Merrimack 10", 3, "ocd-division/country:us/state:nh/sldl:merrimack_10"),
    ("Merrimack 11", 1, "ocd-division/country:us/state:nh/sldl:merrimack_11"),
    ("Merrimack 12", 1, "ocd-division/country:us/state:nh/sldl:merrimack_12"),
    ("Merrimack 13", 1, "ocd-division/country:us/state:nh/sldl:merrimack_13"),
    ("Merrimack 14", 1, "ocd-division/country:us/state:nh/sldl:merrimack_14"),
    ("Merrimack 15", 1, "ocd-division/country:us/state:nh/sldl:merrimack_15"),
    ("Merrimack 16", 1, "ocd-division/country:us/state:nh/sldl:merrimack_16"),
    ("Merrimack 17", 1, "ocd-division/country:us/state:nh/sldl:merrimack_17"),
    ("Merrimack 18", 1, "ocd-division/country:us/state:nh/sldl:merrimack_18"),
    ("Merrimack 19", 1, "ocd-division/country:us/state:nh/sldl:merrimack_19"),
    ("Merrimack 20", 3, "ocd-division/country:us/state:nh/sldl:merrimack_20"),
    ("Merrimack 21", 2, "ocd-division/country:us/state:nh/sldl:merrimack_21"),
    ("Merrimack 22", 1, "ocd-division/country:us/state:nh/sldl:merrimack_22"),
    ("Merrimack 23", 3, "ocd-division/country:us/state:nh/sldl:merrimack_23"),
    ("Merrimack 24", 4, "ocd-division/country:us/state:nh/sldl:merrimack_24"),
    ("Merrimack 25", 1, "ocd-division/country:us/state:nh/sldl:merrimack_25"),
    ("Merrimack 26", 1, "ocd-division/country:us/state:nh/sldl:merrimack_26"),
    ("Merrimack 27", 2, "ocd-division/country:us/state:nh/sldl:merrimack_27"),
    ("Merrimack 28", 1, "ocd-division/country:us/state:nh/sldl:merrimack_28"),
    ("Merrimack 29", 1, "ocd-division/country:us/state:nh/sldl:merrimack_29"),
    ("Rockingham 1", 1, "ocd-division/country:us/state:nh/sldl:rockingham_1"),
    ("Rockingham 2", 3, "ocd-division/country:us/state:nh/sldl:rockingham_2"),
    ("Rockingham 3", 3, "ocd-division/country:us/state:nh/sldl:rockingham_3"),
    ("Rockingham 4", 5, "ocd-division/country:us/state:nh/sldl:rockingham_4"),
    ("Rockingham 5", 7, "ocd-division/country:us/state:nh/sldl:rockingham_5"),
    ("Rockingham 6", 10, "ocd-division/country:us/state:nh/sldl:rockingham_6"),
    ("Rockingham 7", 4, "ocd-division/country:us/state:nh/sldl:rockingham_7"),
    ("Rockingham 8", 9, "ocd-division/country:us/state:nh/sldl:rockingham_8"),
    ("Rockingham 9", 2, "ocd-division/country:us/state:nh/sldl:rockingham_9"),
    ("Rockingham 10", 1, "ocd-division/country:us/state:nh/sldl:rockingham_10"),
    ("Rockingham 11", 1, "ocd-division/country:us/state:nh/sldl:rockingham_11"),
    ("Rockingham 12", 1, "ocd-division/country:us/state:nh/sldl:rockingham_12"),
    ("Rockingham 13", 4, "ocd-division/country:us/state:nh/sldl:rockingham_13"),
    ("Rockingham 14", 4, "ocd-division/country:us/state:nh/sldl:rockingham_14"),
    ("Rockingham 15", 1, "ocd-division/country:us/state:nh/sldl:rockingham_15"),
    ("Rockingham 16", 1, "ocd-division/country:us/state:nh/sldl:rockingham_16"),
    ("Rockingham 17", 3, "ocd-division/country:us/state:nh/sldl:rockingham_17"),
    ("Rockingham 18", 4, "ocd-division/country:us/state:nh/sldl:rockingham_18"),
    ("Rockingham 19", 2, "ocd-division/country:us/state:nh/sldl:rockingham_19"),
    ("Rockingham 20", 3, "ocd-division/country:us/state:nh/sldl:rockingham_20"),
    ("Rockingham 21", 4, "ocd-division/country:us/state:nh/sldl:rockingham_21"),
    ("Rockingham 22", 1, "ocd-division/country:us/state:nh/sldl:rockingham_22"),
    ("Rockingham 23", 1, "ocd-division/country:us/state:nh/sldl:rockingham_23"),
    ("Rockingham 24", 2, "ocd-division/country:us/state:nh/sldl:rockingham_24"),
    ("Rockingham 25", 1, "ocd-division/country:us/state:nh/sldl:rockingham_25"),
    ("Rockingham 26", 1, "ocd-division/country:us/state:nh/sldl:rockingham_26"),
    ("Rockingham 27", 1, "ocd-division/country:us/state:nh/sldl:rockingham_27"),
    ("Rockingham 28", 1, "ocd-division/country:us/state:nh/sldl:rockingham_28"),
    ("Rockingham 29", 1, "ocd-division/country:us/state:nh/sldl:rockingham_29"),
    ("Rockingham 30", 1, "ocd-division/country:us/state:nh/sldl:rockingham_30"),
    ("Rockingham 31", 1, "ocd-division/country:us/state:nh/sldl:rockingham_31"),
    ("Rockingham 32", 1, "ocd-division/country:us/state:nh/sldl:rockingham_32"),
    ("Rockingham 33", 1, "ocd-division/country:us/state:nh/sldl:rockingham_33"),
    ("Rockingham 34", 1, "ocd-division/country:us/state:nh/sldl:rockingham_34"),
    ("Rockingham 35", 1, "ocd-division/country:us/state:nh/sldl:rockingham_35"),
    ("Rockingham 36", 1, "ocd-division/country:us/state:nh/sldl:rockingham_36"),
    ("Rockingham 37", 1, "ocd-division/country:us/state:nh/sldl:rockingham_37"),
    ("Strafford 1", 2, "ocd-division/country:us/state:nh/sldl:strafford_1"),
    ("Strafford 2", 2, "ocd-division/country:us/state:nh/sldl:strafford_2"),
    ("Strafford 3", 2, "ocd-division/country:us/state:nh/sldl:strafford_3"),
    ("Strafford 4", 2, "ocd-division/country:us/state:nh/sldl:strafford_4"),
    ("Strafford 5", 1, "ocd-division/country:us/state:nh/sldl:strafford_5"),
    ("Strafford 6", 5, "ocd-division/country:us/state:nh/sldl:strafford_6"),
    ("Strafford 7", 1, "ocd-division/country:us/state:nh/sldl:strafford_7"),
    ("Strafford 8", 1, "ocd-division/country:us/state:nh/sldl:strafford_8"),
    ("Strafford 9", 1, "ocd-division/country:us/state:nh/sldl:strafford_9"),
    ("Strafford 10", 1, "ocd-division/country:us/state:nh/sldl:strafford_10"),
    ("Strafford 11", 1, "ocd-division/country:us/state:nh/sldl:strafford_11"),
    ("Strafford 12", 1, "ocd-division/country:us/state:nh/sldl:strafford_12"),
    ("Strafford 13", 1, "ocd-division/country:us/state:nh/sldl:strafford_13"),
    ("Strafford 14", 1, "ocd-division/country:us/state:nh/sldl:strafford_14"),
    ("Strafford 15", 1, "ocd-division/country:us/state:nh/sldl:strafford_15"),
    ("Strafford 16", 1, "ocd-division/country:us/state:nh/sldl:strafford_16"),
    ("Strafford 17", 3, "ocd-division/country:us/state:nh/sldl:strafford_17"),
    ("Strafford 18", 3, "ocd-division/country:us/state:nh/sldl:strafford_18"),
    ("Strafford 19", 1, "ocd-division/country:us/state:nh/sldl:strafford_19"),
    ("Strafford 20", 1, "ocd-division/country:us/state:nh/sldl:strafford_20"),
    ("Strafford 21", 1, "ocd-division/country:us/state:nh/sldl:strafford_21"),
    ("Strafford 22", 1, "ocd-division/country:us/state:nh/sldl:strafford_22"),
    ("Strafford 23", 1, "ocd-division/country:us/state:nh/sldl:strafford_23"),
    ("Strafford 24", 1, "ocd-division/country:us/state:nh/sldl:strafford_24"),
    ("Strafford 25", 1, "ocd-division/country:us/state:nh/sldl:strafford_25"),
    ("Sullivan 1", 2, "ocd-division/country:us/state:nh/sldl:sullivan_1"),
    ("Sullivan 2", 1, "ocd-division/country:us/state:nh/sldl:sullivan_2"),
    ("Sullivan 3", 1, "ocd-division/country:us/state:nh/sldl:sullivan_3"),
    ("Sullivan 4", 1, "ocd-division/country:us/state:nh/sldl:sullivan_4"),
    ("Sullivan 5", 1, "ocd-division/country:us/state:nh/sldl:sullivan_5"),
    ("Sullivan 6", 2, "ocd-division/country:us/state:nh/sldl:sullivan_6"),
    ("Sullivan 7", 1, "ocd-division/country:us/state:nh/sldl:sullivan_7"),
    ("Sullivan 8", 1, "ocd-division/country:us/state:nh/sldl:sullivan_8"),
    ("Sullivan 9", 1, "ocd-division/country:us/state:nh/sldl:sullivan_9"),
    ("Sullivan 10", 1, "ocd-division/country:us/state:nh/sldl:sullivan_10"),
    ("Sullivan 11", 1, "ocd-division/country:us/state:nh/sldl:sullivan_11"),
]
