# Return the actor for each action type, or 'chamber' for the bill's home chamber
action_chamber_map = {
    'House': 'upper',
    'Senate': 'lower',
    'RequestforEnactment': 'chamber',
    'IntroducedDate': 'chamber',
    'PreFileDate': 'chamber',
    'Governor': 'executive',
    'Veto': 'executive'
}

status_action_map = {
    'PASSED': 'passage',
    'FAILED': 'failure',
}

action_map = {
    'House1stRead': {'name': 'House First Reading.',
                     'action': ['reading-1']
                     },
    'House1stWaived': {'name': 'House First Reading Waived',
                       'action': ['reading-1']
                       },
    'House2ndRead': {'name': 'House Second Reading',
                     'action': ['reading-2']
                     },
    'House2ndWaived': {'name': 'House Second Reading Waived.',
                       'action': ['reading-2']
                       },
    'HouseCaucusConcurRefuse': {'name': 'House Caucus Refuse to Concur',
                                'action': None,
                                },
    'HouseConsentCalendarDate': {'name': 'House Placed on Consent Calendar',
                                 'action': None,
                                 },
    'HouseConsentCalendarObject': {'name': '',
                                   'action': None,
                                   },
    'HouseConsentObjectDate': {'name': '',
                               'action': None,
                               },
    'HouseMajCaucusDate': {'name': '',
                           'action': None,
                           },
    'HouseMajCaucusDate2': {'name': '',
                            'action': None,
                            },
    'HouseMajCaucusInd': {'name': '',
                          'action': None,
                          },
    'HouseMajCaucusInd2': {'name': '',
                           'action': None,
                           },
    'HouseMinCaucusDate': {'name': '',
                           'action': None,
                           },
    'HouseMinCaucusDate2': {'name': '',
                            'action': None,
                            },
    'HouseMinCaucusInd': {'name': '',
                          'action': None,
                          },
    'HouseMinCaucusInd2': {'name': '',
                           'action': None,
                           },
    'IntroducedDate': {'name': 'Introduced',
                       'action': ['introduced']
                       },
    'PreFileDate': {'name': 'Prefiled.',
                    'action': ['filing']
                    },
    'RequestforEnactment': {'name': 'Request for Enactment',
                            'action': None,
                            },
    'Senate1stRead': {'name': 'Senate First Reading',
                      'action': ['reading-1']
                      },
    'Senate1stWaived': {'name': 'Senate First Reading Waived',
                        'action': ['reading-1']
                        },
    'Senate2ndRead': {'name': 'Senate Second Reading',
                      'action': ['reading-2']
                      },
    'Senate2ndWaived': {'name': 'Senate Second Reading Waived',
                        'action': ['reading-2']
                        },
    'SenateCaucusConcurRefuse': {'name': '',
                                 'action': None,
                                 },
    'SenateConsentCalendarDate': {'name': '',
                                  'action': None,
                                  },
    'SenateConsentCalendarObject': {'name': '',
                                    'action': None,
                                    },
    'SenateConsentObjectDate': {'name': '',
                                'action': None,
                                },
    'SenateMajCaucusDate': {'name': '',
                            'action': None,
                            },
    'SenateMajCaucusDate2': {'name': '',
                             'action': None,
                             },
    'SenateMajCaucusInd': {'name': '',
                           'action': None,
                           },
    'SenateMajCaucusInd2': {'name': '',
                            'action': None,
                            },
    'SenateMinCaucusDate': {'name': '',
                            'action': None,
                            },
    'SenateMinCaucusDate2': {'name': '',
                             'action': None,
                             },
    'SenateMinCaucusInd': {'name': '',
                           'action': None,
                           },
    'SenateMinCaucusInd2': {'name': '',
                            'action': None,
                            },
    'VetoOverride': {'name': 'Veto Overridden',
                     'action': ['veto-override-passage']
                     },
    # TODO: How do we tell signed from vetoed?
    'GovernorAction': {'name': '',
                       'action': None,
                       },
}
