# com_names = {
#     'lower': {'APPROP': 'Appropriations',
#               'AW': 'Agriculture and Water',
#               'BI': 'Banking and Insurance',
#               'COM': 'Commerce',
#               'ED': 'Education',
#               'ENR': 'Energy and Natural Resources',
#               'ENV': 'Environment',
#               'ERA': 'Employment and Regulatory Affairs',
#               'GOV': 'Government',
#               'HEIR': 'Higher Education, Innovation and Reform',
#               'HHS': 'Health and Human Services',
#               'JUD': 'Judiciary',
#               'MAPS': 'Military Affairs and Public Safety',
#               'RULES': 'Rules',
#               'TI': 'Technology and Infrastructure',
#               'TRANS': 'Transportation',
#               'WM': 'Ways and Means'},
#     'upper': {'APPROP': 'Appropriations',
#               'BI': 'Banking and Insurance',
#               'BSFSS': 'Border Security, Federalism and States Sovereignty',
#               'CE': 'Commerce and Energy',
#               'ED': 'Education',
#               'EDJC': 'Economic Development and Jobs Creation',
#               'FIN': 'Finance',
#               'GR': 'Government Reform',
#               'HMLR': 'Healthcare and Medical Liability Reform',
#               'JUD': 'Judiciary',
#               'NRT': 'Natural Resources and Transportation',
#               'PSHS': 'Public Safety and Human Services',
#               'RULES': 'Rules',
#               'SUB APPROP HW': 'Appropriations',
#               'SUB APPROP RIEN': 'Appropriations',
#               'SUB APPROP TCJ': 'Appropriations',
#               'VMA': 'Veterans and Military Affairs',
#               'WLRD': 'Water, Land Use and Rural Development'}}

bill_types = {
    'sb': 'bill',
    'sm': 'memorial',
    'sr': 'resolution',
    'scr': 'concurrent resolution',
    'scm': 'concurrent memorial',
    'scj': 'joint resolution',
    'hb': 'bill',
    'hm': 'memorial',
    'hr': 'resolution',
    'hcr': 'concurrent resolution',
    'hcm': 'concurrent memorial',
    'hjr': 'joint resolution',
    'mis': 'miscellaneous'
}

# Return the actor for each action type, or 'chamber' for the bill's home chamber
action_chamber_map = {
    'House': 'upper',
    'Senate': 'lower',
    'RequestforEnactment': 'chamber',
    'IntroducedDate': 'chamber',
    'PreFileDate': 'chamber',
    'Governor': 'executive',
    'Veto': 'executive'
}

status_action_map = {
    'PASSED': 'passage',
    'FAILED': 'failure',
    'DPA/SE': 'amendment-passage',
    'DPA': 'amendment-passage',
    'DP': 'passage',
    'FP': 'passage',
    'INTRO': 'introduction',
    'AMEND': 'amendment-introduction',
    'W/D': 'withdrawal',
}

action_map = {
    'House1stRead': {'name': 'House First Reading.',
                     'action': ['reading-1']
                     },
    'House1stWaived': {'name': 'House First Reading Waived',
                       'action': ['reading-1']
                       },
    'House2ndRead': {'name': 'House Second Reading',
                     'action': ['reading-2']
                     },
    'House2ndWaived': {'name': 'House Second Reading Waived.',
                       'action': ['reading-2']
                       },
    'HouseCaucusConcurRefuse': {'name': 'House Caucus Refuse to Concur',
                                'action': None,
                                },
    'HouseConsentCalendarDate': {'name': 'House Placed on Consent Calendar',
                                 'action': None,
                                 },
    'HouseConsentCalendarObject': {'name': '',
                                   'action': None,
                                   },
    'HouseConsentObjectDate': {'name': '',
                               'action': None,
                               },
    'HouseMajCaucusDate': {'name': '',
                           'action': None,
                           },
    'HouseMajCaucusDate2': {'name': '',
                            'action': None,
                            },
    'HouseMajCaucusInd': {'name': '',
                          'action': None,
                          },
    'HouseMajCaucusInd2': {'name': '',
                           'action': None,
                           },
    'HouseMinCaucusDate': {'name': '',
                           'action': None,
                           },
    'HouseMinCaucusDate2': {'name': '',
                            'action': None,
                            },
    'HouseMinCaucusInd': {'name': '',
                          'action': None,
                          },
    'HouseMinCaucusInd2': {'name': '',
                           'action': None,
                           },
    'IntroducedDate': {'name': 'Introduced',
                       'action': ['introduced']
                       },
    'PreFileDate': {'name': 'Prefiled.',
                    'action': ['filing']
                    },
    'RequestforEnactment': {'name': 'Request for Enactment',
                            'action': None,
                            },
    'Senate1stRead': {'name': 'Senate First Reading',
                      'action': ['reading-1']
                      },
    'Senate1stWaived': {'name': 'Senate First Reading Waived',
                        'action': ['reading-1']
                        },
    'Senate2ndRead': {'name': 'Senate Second Reading',
                      'action': ['reading-2']
                      },
    'Senate2ndWaived': {'name': 'Senate Second Reading Waived',
                        'action': ['reading-2']
                        },
    'SenateCaucusConcurRefuse': {'name': '',
                                 'action': None,
                                 },
    'SenateConsentCalendarDate': {'name': '',
                                  'action': None,
                                  },
    'SenateConsentCalendarObject': {'name': '',
                                    'action': None,
                                    },
    'SenateConsentObjectDate': {'name': '',
                                'action': None,
                                },
    'SenateMajCaucusDate': {'name': '',
                            'action': None,
                            },
    'SenateMajCaucusDate2': {'name': '',
                             'action': None,
                             },
    'SenateMajCaucusInd': {'name': '',
                           'action': None,
                           },
    'SenateMajCaucusInd2': {'name': '',
                            'action': None,
                            },
    'SenateMinCaucusDate': {'name': '',
                            'action': None,
                            },
    'SenateMinCaucusDate2': {'name': '',
                             'action': None,
                             },
    'SenateMinCaucusInd': {'name': '',
                           'action': None,
                           },
    'SenateMinCaucusInd2': {'name': '',
                            'action': None,
                            },
    'VetoOverride': {'name': 'Veto Overridden',
                     'action': ['veto-override-passage']
                     },
    # TODO: How do we tell signed from vetoed?
    'GovernorAction': {'name': '',
                       'action': None,
                       },
}
