metadata = dict(
    name='Alaska',
    abbreviation='ak',
    legislature_name='The Alaska State Legislature',
    lower_chamber_name='House of Representatives',
    upper_chamber_name='Senate',
    lower_chamber_title='Representative',
    upper_chamber_title='Senator',
    lower_chamber_term=2,
    upper_chamber_term=4,
    terms=[
        dict(name='18', sessions=['18'],
             start_year=1993, end_year=1994),
        dict(name='19', sessions=['19'],
             start_year=1995, end_year=1996),
        dict(name='20', sessions=['20'],
             start_year=1997, end_year=1998),
        dict(name='21', sessions=['21'],
             start_year=1999, end_year=2000),
        dict(name='22', sessions=['22'],
             start_year=2001, end_year=2002),
        dict(name='23', sessions=['23'],
             start_year=2003, end_year=2004),
        dict(name='24', sessions=['24'],
             start_year=2005, end_year=2006),
        dict(name='25', sessions=['25'],
             start_year=2007, end_year=2008),
        dict(name='26', sessions=['26'],
             start_year=2009, end_year=2010),
        ],
    )
