status = dict(
    bills=True,
    bill_versions=True,
    sponsors=True,
    actions=True,
    votes=True,
    legislators=True,
    contributors=['Gabriel J. Perez-Irizarry'],
    notes="",
)

metadata = dict(
    state_name='Washington',
    abbreviation='wa',
    legislature_name='Washington State Legislature',
    upper_chamber_name='Senate',
    lower_chamber_name='House of Representatives',
    upper_chamber_title='Senator',
    lower_chamber_title='Representative',
    upper_chamber_term=4,
    lower_chamber_term=2,
    terms = [
        {'name': '2001',
         'sessions': ['2001 Regular Session'
                      '2001 First Special Session',
                      '2001 Second Special Session'],
         'start_year': 2001, 'end_year': 2001},
        {'name': '2002',
         'sessions': ['2002 Regular Session'],
         'start_year': 2002, 'end_year': 2002},
        {'name': '2003',
         'sessions': ['2003 Regular Session',
                      '2003 First Special Session',
                      '2003 Second Special Session',
                      '2003 Third Special Session'],
         'start_year': 2003, 'end_year': 2003},
        {'name': '2004',
         'sessions': ['2004 Regular Session'],
         'start_year': 2004, 'end_year': 2004},
        {'name': '2005',
         'sessions': ['2005 Regular Session'],
         'start_year': 2005, 'end_year': 2005},
        {'name': '2006',
         'sessions': ['2006 Regular Session'],
         'start_year': 2006, 'end_year': 2006},
        {'name': '2007',
         'sessions': ['2007 Regular Session'],
         'start_year': 2007, 'end_year': 2007},
        {'name': '2008',
         'sessions': ['2008 Regular Session',
                      '2008 First Special Session'],
         'start_year': 2008, 'end_year': 2008},
        {'name': '2009',
         'sessions': ['2009 Regular Session',],
         'start_year': 2009, 'end_year': 2009},
             ]
)

