#!/bin/bash
# Copyright (c) Sunlight Foundation, 2015, under the terms of the BSD-3 license.
#   - Paul Tagliamonte
set -e

mongodump --host ${OPENSTATES_MONGODB} --db ${OPENSTATES_TABLE}
tar cvzf dump.tar.gz dump/
s3cmd -c ${S3_CONFIG} -P put dump.tar.gz s3://${S3_BUCKET}/mongo/latest-mongo-dump.tar.gz
s3cmd -c ${S3_CONFIG} -P put dump.tar.gz s3://${S3_BUCKET}/mongo/`date +%Y-%m-%d`-mongo.tar.gz
