#!/bin/sh
set -e

env

pg_dump -Fc openstatesorg > openstatesorg.pgdump
aws s3 cp openstatesorg.pgdump s3://${S3_BUCKET}/ocd/`date +%Y-%m-%d`-openstatesorg.pgdump


pg_dump -Fc openstatesorg --exclude-table-data 'auth*' --exclude-table-data 'boundaries*' --exclude-table-data 'django_admin*' --exclude-table-data "geo*" --exclude-table-data "simplekeys*" > public.pgdump
aws s3 cp public.pgdump s3://${S3_BUCKET}/public/`date +%Y-%m-%d`-public.pgdump
