sed -i -e 's/bill:introduced/introduction/' $1
sed -i -e 's/bill:passed/passage/' $1
sed -i -e 's/bill:failed/failure/' $1
sed -i -e 's/bill:withdrawn/withdrawal/' $1
sed -i -e 's/bill:substituted/substitution/' $1
sed -i -e 's/bill:filed/filing/' $1
sed -i -e 's/bill:veto_override:passed/veto-override-passage/' $1
sed -i -e 's/bill:veto_override:failed/veto-override-failure/' $1
sed -i -e 's/governor:received/executive-receipt/' $1
sed -i -e 's/governor:signed/executive-signature/' $1
sed -i -e 's/governor:vetoed/executive-veto/' $1
sed -i -e 's/governor:vetoed:line-item/executive-veto-line-item/' $1
sed -i -e 's/amendment:introduced/amendment-introduction/' $1
sed -i -e 's/amendment:passed/amendment-passage/' $1
sed -i -e 's/amendment:failed/amendment-failure/' $1
sed -i -e 's/amendment:tabled/amendment-deferral/' $1
sed -i -e 's/amendment:amended/amendment-amendment/' $1
sed -i -e 's/amendment:withdrawn/amendment-withdrawal/' $1
sed -i -e 's/committee:referred/referral-committee/' $1
sed -i -e 's/committee:passed:favorable/committee-passage-favorable/' $1
sed -i -e 's/committee:passed:unfavorable/committee-passage-unfavorable/' $1
sed -i -e 's/committee:failed/committee-failure/' $1
sed -i -e 's/committee:passed/committee-passage/' $1
sed -i -e 's/bill:reading:1/reading-1/' $1
sed -i -e 's/bill:reading:2/reading-2/' $1
sed -i -e 's/bill:reading:3/reading-3/' $1
