#!/usr/bin/env python

from billy.utils import db

import unicodecsv
import sys

state = sys.argv[1]

dist_csv = unicodecsv.reader(open("manual_data/leg_ids/%s.csv" % (state), 'r'))
for row in dist_csv:
    session, chamber, name, leg_id = row

    eyedee = "%s-%s-%s-%s" % (
        leg_id, name, chamber, session
    )

    db.leg_ids.update({ "_id": eyedee },
                      {
                          "abbr": state,
                          "_id": eyedee,
                          "leg_id": leg_id,
                          "chamber": chamber,
                          "name": name,
                          "session": session
                      },
                      True,  # Upsert
                      safe=True)
