#!/usr/bin/env python

from billy import db
import sys

state = sys.argv[1]

ids = db.manual.leg_ids.find({"abbr": state})

for e in ids:
    if "type" in e:
        continue

    new = e.copy()
    new['type'] = 'legislator'
    db.manual.leg_ids.update(e,
                             new,
                             True)
