#!/usr/bin/env python

import sys
import codecs
from billy.utils import db
from collections import defaultdict

sys.stdout = codecs.getwriter('utf8')(sys.stdout)

spec = {
    "state": "az"
}
bills = db.bills.find(spec)
counts = defaultdict(int)
high_score = 0

print "Date,Count,Pct"

for bill in bills:
    for action in bill['actions']:
        date = action['date'].strftime("%Y-%m-%d")
        actor = action['actor']
        state = bill['state']
        key = "%s" % (
            date
        )
        counts[key] += 1
        if counts[key] > high_score:
            high_score = counts[key]

for line in counts:
    date = line
    count = counts[line]
    print "%s,%s,%s" % (
        date, count, float(count) / float(high_score)
    )
