name: Build and push California Docker image
on:
  push:
    branches:
      - main
    tags:
      - '*'
    paths:
      - "pyproject.toml"
      - "poetry.lock"
      - "Dockerfile.california"
      - "scrapers/ca/*"
      - "scrapers_next/ca/*"
      - ".github/workflows/ca-docker.yml"
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: build california docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile.california
          tags: "openstates/scrapers-california:latest,openstates/scrapers-california:${{ github.sha }}"
          push: true
